# ---------------------------------------------------------------------------
# Title: SAMPLE CLASS
# Authors: Jonathan Amodeo, Hugo Iteney, Javier Gonzalez, Jennifer Izaguirre, Christophe Le Bourlot
# Date: June 01, 2022
#
# The SAMPLE class is responsible for generating the desired object shape (nanowire, slab, sphere, etc.)
# and creating the appropriate file type.
# The MAKE_STL function generates an .stl file of the shape, which is useful for FEM simulations.
# In this method, the shape is created based on user-defined parameters obtained from the PARAM class.
# The MAKE_ATOM function creates an .lmp file, which requires the .stl file generated by MAKE_STL.
# The parameters for generating the .lmp file are determined by the user's input.
# ---------------------------------------------------------------------------
#from tqdm import tqdm
import time
import subprocess
import numpy as np
from src import Func_pyrough as fp

class Sample:
    def __init__(self, type_sample):
        self.sample = type_sample

    def make_stl(
        self,
        type_sample,
        eta,
        C1,
        RMS,
        N,
        M,
        radius,
        length,
        height,
        width,
        ns,
        alpha,
        raw_stl,
        nfaces,
        surfaces,
        energies,
        n_at,
        lattice_structure,
        lattice_parameter,
        material,
        orien_x,
        orien_z,
        out_pre,
        ext_fem,
    ):
        """
        Creates an stl file based on the parameters chosen by the user. Based on the type of sample
        entered, the code will sort through the options of type of samples and if true then the
        code under the type of sample will be executed. The type of sample affects the type of stl
        file returned. The code executed requires the parameters to create the object stl and to
        apply surface roughness onto the object. ...; In continuation will add that a separate
        files will be stored if they want to redo the code.

        :param type_sample: Type of the sample
        :type type_sample: str
        :param eta: Roughness exponent
        :type eta: float
        :param C1: Roughness normalization factor
        :type C1: float
        :param RMS: RMS
        :type RMS: float
        :param N: Length of the random numbers matrix
        :type N: int
        :param M: Length of the random numbers matrix
        :type M: int
        :param radius: The radius of the nanowire or the sphere
        :type radius: float
        :param length: The length of the box
        :type length: float
        :param height: The height of the box
        :type height: float
        :param width: The width of the box
        :type width: float
        :param ns: Mesh size
        :type ns: float
        :param alpha: Refine mesh factor
        :type alpha: float
        :param raw_stl: Input STL file
        :type raw_stl: stl
        :param nfaces: Number of faces in the case of a faceted wire
        :type nfaces: int
        :param surfaces: List of surfaces used for Wulff theory
        :type surfaces: list
        :param energies: List of energies for each associated surface
        :type energies: list
        :param n_at: Number of atoms in the case of a faceted NP
        :type n_at: int
        :param lattice_structure: Crystallographic structure of the material
        :type lattice_structure: str
        :param lattice_parameter: Lattice parameter of the material
        :type lattice_parameter: float
        :param material: Type of material
        :type material: str
        :param orien_x: Orientation along x-axis
        :type orien_x: list
        :param orien_z: Orientation along z-axis
        :type orien_z: list
        :param out_pre: Prefix of the output files
        :type out_pre: str
        :param ext_fem: Output FEM formats list
        :type ext_fem: list

        :returns: List of nodes and stl file name
        """
        if type_sample == "wire":
            vertices, stl = make_wire(
                type_sample,
                2 * (1 + eta),
                C1,
                RMS,
                N,
                M,
                radius,
                length,
                ns,
                alpha,
                raw_stl,
                out_pre,
                ext_fem,
            )

            return (vertices, stl)

        elif type_sample == "box":
            vertices, stl = make_box(
                type_sample,
                2 * (1 + eta),
                C1,
                RMS,
                N,
                M,
                length,
                height,
                width,
                ns,
                alpha,
                raw_stl,
                out_pre,
                ext_fem,
            )

            return (vertices, stl)

        elif type_sample == "sphere":
            vertices, stl = make_sphere(
                type_sample,
                4 * eta,
                C1,
                N,
                radius,
                ns,
                alpha,
                raw_stl,
                out_pre,
                ext_fem,
            )

            return (vertices, stl)

        elif type_sample == "poly":
            vertices, stl = make_poly(
                type_sample,
                2 * (1 + eta),
                C1,
                RMS,
                N,
                M,
                length,
                nfaces,
                radius,
                ns,
                alpha,
                raw_stl,
                out_pre,
                ext_fem,
            )
            return (vertices, stl)

#---------------------------------------------------------------------------------------------------------------------------------------------------------
        elif type_sample == "poly_pillar":
            if type(eta) == int or type(eta) == float :
                vertices, stl = make_poly_pillar(
                        type_sample,
                        2*(1+eta),
                        2*(1+eta),
                        C1,
                        C1,
                        RMS,
                        RMS,
                        N,
                        M,
                        length,
                        nfaces,
                        radius,
                        ns,
                        alpha,
                        raw_stl,
                        out_pre,
                        ext_fem,
                )
            else :
                vertices, stl = make_poly_pillar(
                        type_sample,
                        2*(1+eta[0]),
                        2*(1+eta[1]),
                        C1[0],
                        C1[1],
                        RMS[0],
                        RMS[1],
                        N,
                        M,
                        length,
                        nfaces,
                        radius,
                        ns,
                        alpha,
                        raw_stl,
                        out_pre,
                        ext_fem,
                )

            return (vertices, stl)

        elif type_sample == "pillar":
            if type(eta) == int or type(eta) == float :
                vertices, stl = make_pillar(
                        type_sample,
                        2*(1+eta),
                        2*(1+eta),
                        C1,
                        C1,
                        RMS,
                        RMS,
                        N,
                        M,
                        length,
                        nfaces,
                        radius,
                        ns,
                        alpha,
                        raw_stl,
                        out_pre,
                        ext_fem,
                )
            else :
                vertices, stl = make_pillar(
                    type_sample,
                    2 * (1 + eta[0]),
                    2 * (1 + eta[1]),
                    C1[0],
                    C1[1],
                    RMS[0],
                    RMS[1],
                    N,
                    M,
                    length,
                    nfaces,
                    radius,
                    ns,
                    alpha,
                    raw_stl,
                    out_pre,
                    ext_fem,
                )
            return (vertices, stl)


#---------------------------------------------------------------------------------------------------------------------------------------------------------

        elif type_sample == "wulff":
            vertices, stl = make_wulff(
                type_sample,
                2 * (1 + eta),
                C1,
                RMS,
                N,
                M,
                surfaces,
                energies,
                n_at,
                ns,
                alpha,
                raw_stl,
                lattice_structure,
                lattice_parameter,
                material,
                orien_x,
                orien_z,
                out_pre,
                ext_fem,
            )

            return (vertices, stl)

        elif type_sample == "cube":
            vertices, stl = make_cube(
                type_sample,
                2 * (1 + eta),
                C1,
                RMS,
                N,
                M,
                length,
                ns,
                alpha,
                raw_stl,
                out_pre,
                ext_fem,
            )

            return (vertices, stl)

    def make_atom(
        self,
        STL,
        lattice_str,
        lattice_par,
        material,
        orien_x,
        orien_y,
        orien_z,
        vertices,
        out_pre,
        ext_ato,
    ):
        """
        Creates an atom position file sample_with_atoms.lmp. This requires a .stl file with rough surfaces
        used as a stencil over a larger block of atoms from which out-of-the-mesh atoms are removed

        :param type_sample: Sample type
        :type type_sample: str
        :param STL: The stl file with an object that has surface roughness applied to it
        :type STL: str
        :param lattice_str: The lattice structure of the crystal
        :type lattice_str: str
        :param lattice_par: The lattice parameter of the crystal in Angstrom
        :type lattice_par: float
        :param material: The chemical symbol of the desired element
        :type material: str
        :param orien_x: The orientation of the crystal in the x direction
        :type orien_x: list
        :param orien_y: The orientation of the crystal in the y direction
        :type orien_y: list
        :param orien_z: The orientation of the crystal in the z direction
        :type orien_z: list
        :param vertices: List of nodes
        :type vertices: array
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """

        dim_x = max(vertices[:, 0]) - min(vertices[:, 0])
        dim_y = max(vertices[:, 1]) - min(vertices[:, 1])
        dim_z = max(vertices[:, 2]) - min(vertices[:, 2])
        dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x, lattice_par, lattice_str)
        dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y, lattice_par, lattice_str)
        dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z, lattice_par, lattice_str)

        # Here we create a large block of atoms material_supercell.lmp
        cmd = [
            "atomsk",
            "--create",
            lattice_str,
            *lattice_par,
            *material,
            "orient",
            orien_x,
            orien_y,
            orien_z,
            "-duplicate",
            dup_x,
            dup_y,
            dup_z,
            "material_supercell.lmp",
            "-v ",
            "2",
        ]

        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over material_supercell.lmp and extra atoms are removed
        cmd = [
                "atomsk",
                "material_supercell.lmp",
                "-select",
                "stl",
                "center",
                STL,
                "-select",
                "invert",
                "-rmatom",
                "select",
                out_pre + ".lmp",
                " ".join([x for x in ext_ato[0:] if x != "lmp"]),
                "-v ",
                "2",
            ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        subprocess.call(["rm", "material_supercell.lmp"])

        fp.rebox(out_pre + ".lmp", 0.001)

    def make_precipitate(
        self,
        STL,
        lattice_str,
        lattice_par,
        material,
        orien_x,
        orien_y,
        orien_z,
        dim_mat_x,
        dim_mat_y,
        dim_mat_z,
    ):
        """
        Creates an atom position file sample_with_atoms.lmp. This requires a .stl file with rough surfaces
        used as a stencil over a larger block of atoms from which out-of-the-mesh atoms are removed

        :param type_sample: Sample type
        :type type_sample: str
        :param STL: The stl file with an object that has surface roughness applied to it
        :type STL: str
        :param lattice_str: The lattice structure of the crystal
        :type lattice_str: str
        :param lattice_par: The lattice parameter of the crystal in Angstrom
        :type lattice_par: float
        :param material: The chemical symbol of the desired element
        :type material: str
        :param orien_x: The orientation of the crystal in the x direction
        :type orien_x: list
        :param orien_y: The orientation of the crystal in the y direction
        :type orien_y: list
        :param orien_z: The orientation of the crystal in the z direction
        :type orien_z: list
        :param out_pre: Prefix of the output files
        :type out_pre: str
        :param dim_mat_x: Dimensions of the matrix
        :type dim_mat_x: float
        """

        dis_x, dup_x, orien_x = fp.duplicate(dim_mat_x, orien_x, lattice_par, lattice_str)
        dis_y, dup_y, orien_y = fp.duplicate(dim_mat_y, orien_y, lattice_par, lattice_str)
        dis_z, dup_z, orien_z = fp.duplicate(dim_mat_z, orien_z, lattice_par, lattice_str)

        cmd = [
            "atomsk",
            "--create",
            lattice_str,
            *lattice_par,
            *material,
            "orient",
            orien_x,
            orien_y,
            orien_z,
            "-duplicate",
            dup_x,
            dup_y,
            dup_z,
            "precipitate_supercell.xyz",
            "-v ",
            "2",
        ]

        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over precipitate_supercell.lmp and extra atoms are removed
        cmd = [
                "atomsk",
                "precipitate_supercell.xyz",
                "-select",
                "stl",
                "center",
                STL,
                "-select",
                "invert",
                "-rmatom",
                "select",
                "precipitate.xyz",
                "-v",
                "2",
        ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        subprocess.call(["rm", "precipitate_supercell.xyz"])

    def make_atom_matrix(
        self,
        STL,
        length_x,
        length_y,
        length_z,
        lattice_str,
        lattice_par,
        material,
        orien_x,
        orien_y,
        orien_z,
    ):
        """
        Creates an orthogonal matrix made of atoms.

        :param length_x: Sample dimension
        :type length_x: float
        :param length_y: Sample dimension
        :type length_y: float
        :param length_z: Sample dimension
        :type length_z: float
        :param lattice_str: The lattice structure of the crystal
        :type lattice_str: str
        :param lattice_par: The lattice parameter of the crystal in Angstrom
        :type lattice_par: float
        :param material: The chemical symbol of the desired element
        :type material: str
        :param orien_x: The orientation of the crystal in the x direction
        :type orien_x: list
        :param orien_y: The orientation of the crystal in the y direction
        :type orien_y: list
        :param orien_z: The orientation of the crystal in the z direction
        :type orien_z: list
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """

        dis_x, dup_x, orien_x = fp.duplicate(length_x, orien_x, lattice_par, lattice_str)
        dis_y, dup_y, orien_y = fp.duplicate(length_y, orien_y, lattice_par, lattice_str)
        dis_z, dup_z, orien_z = fp.duplicate(length_z, orien_z, lattice_par, lattice_str)

        # Creation of a matrix of atoms i.e., a large orthogonal block of atoms
        cmd =  [
                "atomsk",
                "--create",
                lattice_str,
                *lattice_par,
                *material,
                "orient",
                orien_x,
                orien_y,
                orien_z,
                "-duplicate",
                dup_x,
                dup_y,
                dup_z,
                "matrix_tmp.xyz",
                "-v",
                "2",
            ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over material_supercell.lmp and extra atoms are removed
        cmd = [
            "atomsk",
            "matrix_tmp.xyz",
            "-select",
            "stl",
            "center",
            STL,
            "-rmatom",
            "select",
            "matrix.xyz",
            "-v",
            "2",

        ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        subprocess.call(["rm", "matrix_tmp.xyz"])

    def put_prec_in_matrix(
            self,
            out_pre,
            ext_ato
    ):
        """
        Introduce a cube/sphere/wulff precipitate into a matrix

        :param out_pre_matrix: Matrix sample
        :type out_pre_matrix: str
        :param STL: The stl file with an object that has surface roughness
        :type STL: str
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """
        # This atomsk call use the same STL file than for block 1 to carve out part of out_pre_matrix into mat2_out.xyz
        # As using thee same STL file but with the invert option, mat2_out.xyz is the negative of mat1_out.xyz
        cmd = [
            "atomsk",
            "--merge",
            "2",
            "matrix.xyz",
            "precipitate.xyz",
             out_pre + ".xyz",
            "-v",
            "2",
        ]
        print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        subprocess.call(["atomsk", out_pre + ".xyz", out_pre + ".lmp"])

        for e in ext_ato:
            if e != "lmp":
                subprocess.call(["atomsk", out_pre + ".lmp", out_pre + "." + e, "-v","2"])

        subprocess.call(["rm", "matrix.xyz", "precipitate.xyz", out_pre + ".xyz"])


def make_wire(type_sample, B, C1, RMS, N, M, radius, length, ns, alpha, raw_stl, out_pre, ext_fem):
    """
    Creates an stl file of a rough wire

    :param type_sample: The name of the sample
    :type type_sample: str
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param radius: Radius of the wire
    :type radius: float
    :param length: Length of the box
    :type length: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """
    vertices, faces = fp.read_stl(type_sample, raw_stl, 0, length, 0, radius, ns, 0)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array file
    # from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(type_sample, vertices, nodenumber, 0, 0)

    # convert to cylindrics coordinates (Rho Theta Z nodenumb)
    cy_nodesurf = np.array(
        [
            fp.rho(nodesurf[:, 0], nodesurf[:, 1]),
            fp.theta(nodesurf[:, 0], nodesurf[:, 1]),
            nodesurf[:, 2],
            nodesurf[:, 3],
        ]
    ).T

    cy_nodesurf = cy_nodesurf[np.lexsort((cy_nodesurf[:, 1], cy_nodesurf[:, 2]))]

    # creating X and Y vector (Connection matrix size) going to make one line code
    xv = (cy_nodesurf[:, 1] / max(cy_nodesurf[:, 1]) + 1) / 2
    yv = (cy_nodesurf[:, 2] / max(cy_nodesurf[:, 2]) + 1) / 2

    sfrN, sfrM = fp.vectors(N, M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(type_sample, m, n, N, M, B, xv, yv, sfrM, sfrN, C1, RMS, out_pre)
    vertices = fp.make_rough(type_sample, z, cy_nodesurf, vertices, 0)

    # gets ride of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates an stl file of the cylinder with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)

    return vertices, out_pre + ".stl"


def make_box(
    type_sample,
    B,
    C1,
    RMS,
    N,
    M,
    length,
    height,
    width,
    ns,
    alpha,
    raw_stl,
    out_pre,
    ext_fem,
):
    """
    Creates an stl file of a rough box

    :param type_sample: The name of the sample
    :type type_sample: str
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Length of the box
    :type length: float
    :param height: Height of the box
    :type height: float
    :param width: Width of the box
    :type width: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """
    vertices, faces = fp.read_stl(type_sample, raw_stl, width, length, height, 0, ns, 0)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(type_sample, vertices, nodenumber, 0, 0)
    nodesurf = nodesurf[np.lexsort((nodesurf[:, 0], nodesurf[:, 1]))]

    xv = nodesurf[:, 0] / max(nodesurf[:, 0])
    yv = nodesurf[:, 1] / max(nodesurf[:, 1])

    sfrN, sfrM = fp.vectors(N, M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(type_sample, m, n, N, M, B, xv, yv, sfrM, sfrN, C1, RMS, out_pre)
    vertices = fp.make_rough(type_sample, z, nodesurf, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates an stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)
    return vertices, out_pre + ".stl"


def make_sphere(type_sample, B, C1, N, radius, ns, alpha, raw_stl, out_pre, ext_fem):
    """
    Creates an stl file of a rough sphere

    :param type_sample: The name of the sample
    :type type_sample: str
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param N: Scaling cartesian position
    :type N: int
    :param radius: Radius of the sphere
    :type radius: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """
    vertices, faces = fp.read_stl(type_sample, raw_stl, 0, 0, 0, radius, ns, 0)
    nbPoint = len(vertices)

    r = np.zeros(nbPoint)
    x, y, z, t = fp.coord_sphere(vertices)
    vert_phi_theta = fp.vertex_tp(x, y, t, z)

    thetaa = fp.theta(y, x)
    phii = fp.phi(t, z)

    # creates the displacement values of the nodes on the surface of the sphere
    r = fp.rough_matrix_sphere(nbPoint, B, thetaa, phii, vert_phi_theta, r)

    # creates a new matrix with x, y, z in cartesian coordinates
    C2 = 1.0 / nbPoint / N / 2.0
    new_vertex = fp.coord_cart_sphere(C1, C2, r, vertices, t, z, y, x)

    # creates an stl file of the sphere with roughness on the surface
    fp.stl_file(new_vertex, faces, out_pre)
    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)
    return vertices, out_pre + ".stl"


def make_poly(
    type_sample,
    B,
    C1,
    RMS,
    N,
    M,
    length,
    nfaces,
    radius,
    ns,
    alpha,
    raw_stl,
    out_pre,
    ext_fem,
):
    """
    Creates an stl file of a rough faceted wire

    :param type_sample: The name of the sample
    :type type_sample: str
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Length of the wire
    :type length: float
    :param nfaces: Number of faces of the wire
    :type nfaces: int
    :param radius: Radius of the wire
    :type radius: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """
    points, angles = fp.base(radius, nfaces)

    vertices, faces = fp.read_stl(type_sample, raw_stl, 0, length, 0, radius, ns, points)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(
        type_sample,
        vertices,
        nodenumber,
        points,
        0,
    )
    cy_nodesurf = fp.cart2cyl(nodesurf)
    sorted_cy_nodesurf = cy_nodesurf[np.lexsort((cy_nodesurf[:, 1], cy_nodesurf[:, 2]))]
    nodesurf = fp.cyl2cart(sorted_cy_nodesurf)

    Z = len(np.where(sorted_cy_nodesurf[:, 2] == 0)[0])
    T = len(np.unique(sorted_cy_nodesurf[:, 2]))
    xv = np.linspace(0, 1, Z)
    yv = np.linspace(0, 1, T)

    xv, yv = np.meshgrid(xv, yv)

    sfrN, sfrM = fp.vectors(N, M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(type_sample, m, n, N, M, B, xv, yv, sfrM, sfrN, C1, RMS, out_pre)
    vertices = fp.make_rough(type_sample, z, nodesurf, vertices, angles)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]
    vertices = fp.align_poly(vertices, angles)

    # creates an stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)

    return vertices, out_pre + ".stl"

def make_wulff(
    type_sample,
    B,
    C1,
    RMS,
    N,
    M,
    surfaces,
    energies,
    n_at,
    ns,
    alpha,
    raw_stl,
    lattice_structure,
    lattice_parameter,
    material,
    orien_x,
    orien_z,
    out_pre,
    ext_fem,
):
    """
    Creates an stl file of a rough Wulff-shaped nanoparticle

    :param type_sample: The name of the sample
    :type type_sample: str
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param surfaces: Orientation of surfaces used for Wulff theory
    :type surfaces: list
    :param energies: Energies of associated surfaces for Wulff theory
    :type energies: list
    :param n_at: Number of atoms
    :type n_at: int
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param lattice_structure: The lattice structure of the crystal
    :type lattice_structure: str
    :param lattice_parameter: The lattice parameter of the crystal in Angstrom
    :type lattice_parameter: float
    :param material: The chemical symbol of the desired element
    :type material: str
    :param orien_x: Orientation along x-axis
    :type orien_x: list
    :param orien_z: Orientation along z-axis
    :type orien_z: list
    :param out_pre: Prefix for output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """
    obj_points, obj_faces = fp.make_obj(
        surfaces,
        energies,
        n_at,
        lattice_structure,
        lattice_parameter,
        material,
        orien_x,
        orien_z,
        out_pre,
    )
    vertices, faces = fp.read_stl_wulff(raw_stl, obj_points, obj_faces, ns)
    subprocess.call(["rm", out_pre + ".obj"])
    list_n = fp.faces_normals(obj_points, obj_faces)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)
    nodesurf = fp.node_surface(type_sample, vertices, nodenumber, obj_points, obj_faces)

    node_edge, node_corner = fp.node_corner(nodesurf)

    vertices = fp.make_rough_wulff(
        vertices, B, C1, RMS, N, M, nodesurf, node_edge, node_corner, list_n
    )

    vertices = vertices[:, :3]

    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)

    return vertices, out_pre + ".stl"


def make_cube(type_sample, B, C1, RMS, N, M, length, ns, alpha, raw_stl, out_pre, ext_fem):
    """
    Creates an stl file of a cubic NP

    :param type_sample: The name of the sample
    :type type_sample: str
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Dimension of the cube
    :type length: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """

    obj_points, obj_faces = fp.cube_faces(length)
    list_n = fp.faces_normals(obj_points, obj_faces)

    vertices, faces = fp.read_stl(type_sample, raw_stl, 0, length, 0, 0, ns, 0)
    vertices, nodenumber = fp.node_indexing(vertices)

    nodesurf = fp.node_surface(type_sample, vertices, nodenumber, obj_points, obj_faces)
    node_edge, node_corner = fp.node_corner(nodesurf)

    vertices = fp.make_rough_wulff(
        vertices, B, C1, RMS, N, M, nodesurf, node_edge, node_corner, list_n
    )

    vertices = fp.center_3d_dataset(vertices[:, :3])

    fp.stl_file(vertices, faces, out_pre)

    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)

    return (vertices, out_pre + ".stl")

def make_atom_grain(
    STL,
    lattice_structure1,
    lattice_parameter1,
    material1,
    orien_x1,
    orien_y1,
    orien_z1,
    lattice_structure2,
    lattice_parameter2,
    material2,
    orien_x2,
    orien_y2,
    orien_z2,
    vertices,
    out_pre,
    ext_ato,
):
    """
    Generates an atomic positions file for the grain object.

    :param STL: The stl file with an object that has surface roughness applied to it
    :type STL: str
    :param lattice_structure1: The lattice structure of the crystal 1
    :type lattice_structure1: str
    :param lattice_parameter1: The lattice parameter of the crystal 1 in Angstrom
    :type lattice_parameter1: float
    :param material1: The chemical symbol of the desired element 1
    :type material1: str
    :param orien_x1: The orientation of the crystal 1 in the x direction
    :type orien_x1: list
    :param orien_y1: The orientation of the crystal 1 in the y direction
    :type orien_y1: list
    :param orien_z1: The orientation of the crystal 1 in the z direction
    :type orien_z1: list
    :param lattice_structure2: The lattice structure of the crystal 2
    :type lattice_structure2: str
    :param lattice_parameter2: The lattice parameter of the crystal 2 in Angstrom
    :type lattice_parameter2: float
    :param material2: The chemical symbol of the desired element 2
    :type material2: str
    :param orien_x2: The orientation of the crystal 2 in the x direction
    :type orien_x2: list
    :param orien_y2: The orientation of the crystal 2 in the y direction
    :type orien_y2: list
    :param orien_z2: The orientation of the crystal 2 in the z direction
    :type orien_z2: list
    :param vertices: List of nodes
    :type vertices: array
    :param out_pre: Prefix of output file
    :type out_pre: str
    :param ext_ato: Atomic position file format list
    :type ext_ato: list

    :return:
    """
    dim_x = max(vertices[:, 0]) - min(vertices[:, 0])
    dim_y = max(vertices[:, 1]) - min(vertices[:, 1])
    dim_z = max(vertices[:, 2]) - min(vertices[:, 2])
    dis_x1, dup_x1, orien_x1 = fp.duplicate(dim_x, orien_x1, lattice_parameter1, lattice_structure1)
    dis_y1, dup_y1, orien_y1 = fp.duplicate(dim_y, orien_y1, lattice_parameter1, lattice_structure1)
    dis_z1, dup_z1, orien_z1 = fp.duplicate(2 * dim_z, orien_z1, lattice_parameter1, lattice_structure1)
    dis_x2, dup_x2, orien_x2 = fp.duplicate(dim_x, orien_x2, lattice_parameter2, lattice_structure2)
    dis_y2, dup_y2, orien_y2 = fp.duplicate(dim_y, orien_y2, lattice_parameter2, lattice_structure2)
    dis_z2, dup_z2, orien_z2 = fp.duplicate(2 * dim_z, orien_z2, lattice_parameter2, lattice_structure2)

    # Here we generate the main block : mat1_supercell.cfg
    subprocess.call(
        [
            "atomsk",
            "--create",
            lattice_structure1,
            *lattice_parameter1,
            *material1,
            "orient",
            orien_x1,
            orien_y1,
            orien_z1,
            "-duplicate",
            dup_x1,
            dup_y1,
            dup_z1,
            "-center",
            "com",
            "mat1_supercell.cfg",
            "-v",
            "2",
        ]
    )

    # Here we generate the second block : mat2_supercell.cfg
    subprocess.call(
        [
            "atomsk",
            "--create",
            lattice_structure2,
            *lattice_parameter2,
            *material2,
            "orient",
            orien_x2,
            orien_y2,
            orien_z2,
            "-duplicate",
            dup_x2,
            dup_y2,
            dup_z2,
            "-center",
            "com",
            "mat2_supercell.cfg",
            "-v",
            "2",
        ]
    )

    # We deform mat2_supercell.cfg to match mat1_supercell.cfg dimensions and preserve PBCs
    fp.strain_file1_to_file2("mat2_supercell.cfg","mat1_supercell.cfg")

    # Atomsk uses the .stl file to carve out a part of mat1_supercell.cfg that becomes a rough block (mat1_out.cfg)
    subprocess.call(
        [
            "atomsk",
            "mat1_supercell.cfg",
            "-select",
            "stl",
            STL,
            "-rmatom",
            "select",
            "mat1_out.cfg",
            "-v",
            "2",
        ]
    )

    # Here we use the same .stl file to carve out part of mat2_supercell.cfg that becomes a rough block (mat2_out.cfg)
    # Thus, mat2_out.cfg is the negative of mat1_out.cfg
    subprocess.call(
        [
            "atomsk",
            "mat2_supercell.cfg",
            "-select",
            "stl",
            STL,
            "-select",
            "invert",
            "-rmatom",
            "select",
            "mat2_out.cfg",
            "-v",
            "2",
        ]
    )

    # Merging of mat1_out.cfg and mat2_out.cfg
    subprocess.call(["atomsk", "--merge", "2", "mat1_out.cfg", "mat2_out.cfg", "temp2.cfg", "-v","2"])

    for e in ext_ato:
        subprocess.call(["atomsk", "temp2.cfg", out_pre + "." + e, "-v","2"])

    # Cleaning
    subprocess.call(
        [
            "rm",
            "mat1_supercell.cfg",
            "mat2_supercell.cfg",
            "mat1_out.cfg",
            "mat2_out.cfg",
            "temp2.cfg",
        ]
    )



#------------------------------------------------------------------------------------------------------------------------------------------------------

def make_poly_pillar(
        type_sample,
        B1,
        B2,
        C1,
        C2,
        RMS1,
        RMS2,
        N,
        M,
        length,
        nfaces,
        radius,
        ns,
        alpha,
        raw_stl,
        out_pre,
        ext_fem,
):
    """        
    :type type_sample: str
    :param B1: The degree the roughness is dependent on for the lateral surface
    :type B1: float
    :param B2: The degree the roughness is dependent on for the upside surface
    :type B2: float
    :param C1: Roughness normalization factor for the lateral surface
    :type C1: float
    :param C2: Roughness normalization factor for the upside surface
    :type C2: float
    :param RMS1: RMS1
    :type RMS1: float
    :param RMS2: RMS2
    :type RMS2: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Length of the wire
    :type length: float
    :param nfaces: Number of faces of the wire
    :type nfaces: int
    :param radius: Radius of the wire
    :type radius: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name for a Faceted Pillar
    """
    #create the base of the faceted Pillar
    points, angles = fp.base(radius,nfaces)

    vertices, faces = fp.read_stl(type_sample,raw_stl,0,length,0,radius,ns,points)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumber which is an array
    # filled from 0 - length of the vertices
    vertices , nodenumber = fp.node_indexing(vertices)

    #nodes at the surface of the object. These nodes will have the surface roughness applied to it
    #nodesurf 1 is the faceted wire surface, and nodesurf2 is the topside surface
    nodesurf1 = fp.node_surface("poly",vertices,nodenumber,points,0)
    nodesurf2 = fp.node_surface("box",vertices,nodenumber,0,0)

   #Save the index of nodes which are on the edge of the pillar
    nodesurftot = [nodesurf1] + [nodesurf2]
    node_edge, node_corner = fp.node_corner(nodesurftot)

    # convert to cylindrics coordinates (Rho Theta Z nodenumber)
    cy_nodesurf1 = fp.cart2cyl(nodesurf1)
    sorted_cy_nodesurf1 = cy_nodesurf1[np.lexsort((cy_nodesurf1[:,1],cy_nodesurf1[:,2]))]
    nodesurf1 = fp.cyl2cart(sorted_cy_nodesurf1)

    Z = len(np.where(sorted_cy_nodesurf1[:,2] ==0)[0])
    T = len(np.unique(sorted_cy_nodesurf1[:,2]))

    xv1 = np.linspace(0,1,Z)
    yv1 = np.linspace(0,1,T)
    xv1, yv1 = np.meshgrid(xv1,yv1)
    sfrN, sfrM = fp.vectors(N,M) # creating vectors for M and N
    m1,n1 = fp.random_numbers(sfrN, sfrM) # normal gaussian for the amplitude


    xv2 = nodesurf2[:, 0] / max(nodesurf2[:, 0])
    yv2 = nodesurf2[:, 1] / max(nodesurf2[:, 1])
    m2, n2 = fp.random_numbers(sfrN,sfrM) # normal gaussian for the amplitude

    #Returns an array with the Z values that will replace the previous z values in the vertices
    #Array these represent the roughness on the surface
    z1 = fp.random_surf2("poly",m1,n1,N,M,B1,xv1,yv1,sfrM,sfrN,C1,RMS1,out_pre)
    z2 = fp.random_surf2("box",m2,n2,N,M,B2,xv2,yv2,sfrM,sfrN,C2,RMS2,out_pre)

    #Displace nodes to make surfaces rough, nodes on the edge are displace 2 times so these displacement should be normalised
    vertices = fp.make_rough_pillar(type_sample,z1,z2,nodesurf1,nodesurf2,node_edge,vertices,angles)
    #gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:,:3]

    vertices = fp.align_poly(vertices,angles)
    fp.stl_file(vertices,faces,out_pre)
    fp.refine_3Dmesh(type_sample,out_pre,ns,alpha,ext_fem)
    return (vertices, out_pre + ".stl")

    

    #------------------------------------------------------------------------------------------------------------------------------------------------------
def make_pillar(
        type_sample,
        B1,
        B2,
        C1,
        C2,
        RMS1,
        RMS2,
        N,
        M,
        length,
        nfaces,
        radius,
        ns,
        alpha,
        raw_stl,
        out_pre,
        ext_fem,
):
    """
    :type type_sample: str
    :param B1: The degree the roughness is dependent on for the lateral surface
    :type B1: float
    :param B2: The degree the roughness is dependent on for the upside surface
    :type B2: float
    :param C1: Roughness normalization factor for the lateral surface
    :type C1: float
    :param C2: Roughness normalization factor for the upside surface
    :type C2: float
    :param RMS1: RMS1
    :type RMS1: float
    :param RMS2: RMS2
    :type RMS2: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Length of the wire
    :type length: float
    :param nfaces: Number of faces of the wire
    :type nfaces: int
    :param radius: Radius of the wire
    :type radius: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name for a circular Pillar
    """
    vertices, faces = fp.read_stl(type_sample, raw_stl, 0, length, 0, radius, ns, 0)

    # Creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumber which is an array file
    # from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    #Nodes at the surface of the object. These nodes will have the surface roughness applied to it
    #nodesurf 1 is the wire surface, and nodesurf2 is the topside surface
    nodesurf1 = fp.node_surface("wire", vertices, nodenumber, 0, 0)
    nodesurf2 = fp.node_surface("box", vertices, nodenumber, 0, 0)

    #Getting the index of nodes on the edge
    nodesurftot = [nodesurf1] + [nodesurf2]
    node_edge, node_corner = fp.node_corner(nodesurftot)

    #Convert to cylindrics coordinates (Rho Theta Z nodenumber)
    cy_nodesurf1 = np.array(
        [
            fp.rho(nodesurf1[:, 0], nodesurf1[:, 1]),
            fp.theta(nodesurf1[:, 0], nodesurf1[:, 1]),
            nodesurf1[:, 2],
            nodesurf1[:, 3],
        ]
    ).T

    cy_nodesurf1 = cy_nodesurf1[np.lexsort((cy_nodesurf1[:, 1], cy_nodesurf1[:, 2]))]

    #Creating X and Y vector (Connection matrix size) going to make one line code
    xv1 = (cy_nodesurf1[:, 1] / max(cy_nodesurf1[:, 1]) + 1) / 2
    yv1 = (cy_nodesurf1[:, 2] / max(cy_nodesurf1[:, 2]) + 1) / 2

    sfrN, sfrM = fp.vectors(N, M)  # creating vectors for M and N
    m1, n1 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude


    xv2 = nodesurf2[:, 0] / max(nodesurf2[:, 0])
    yv2 = nodesurf2[:, 1] / max(nodesurf2[:, 1])
    m2, n2 = fp.random_numbers(sfrN,sfrM)


    #Returns an array with the Z values that will replace the previous z values in the vertices
    #Array these represent the roughness on the surface
    z1 = fp.random_surf2("wire", m1, n1, N, M, B1, xv1, yv1, sfrM, sfrN, C1, RMS1, out_pre)
    z2 = fp.random_surf2("box", m2, n2, N, M, B2, xv2, yv2, sfrM, sfrN, C2, RMS2, out_pre)

    vertices = fp.make_rough_pillar(type_sample,z1,z2,cy_nodesurf1,nodesurf2,node_edge,vertices,0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates a stl file of the cylinder with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(type_sample, out_pre, ns, alpha, ext_fem)

    return vertices, out_pre + ".stl"



def make_multi_layered(
        type_sample,
        j,
        h,
        B,
        C1,
        RMS,
        N,
        M,
        length,
        height,
        width,
        ns,
        alpha,
        raw_stl,
        out_pre,
        ext_fem,
):
    """
    Creates an stl file of a rough box using to make a multi_layered grain

    :param type_sample: The name of the sample
    :type type_sample: str
    :param j : the index of the box stl used to build the final Multi_layered Device
    :type j : int
    :param h : Initial height z_min == h
    :type h : float
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Length of the box
    :type length: float
    :param height: Height of the box
    :type height: float
    :param width: Width of the box
    :type width: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of nodes and STL file name
    """
    #Create a box perfect mesh at an initial height h
    vertices, faces = fp.multi_layered(h,width, length, height, ns)

    #Creates a column that has an assigned index number for each row in vertices
    #with the addition of this new column and also returns the nodenumber which is an array
    #filled from 0 - length of the vertices

    vertices, nodenumber = fp.node_indexing(vertices)


    #Nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(type_sample, vertices, nodenumber, 0, 0)
    nodesurf = nodesurf[np.lexsort((nodesurf[:, 0], nodesurf[:, 1]))]

    xv = nodesurf[:, 0] / max(nodesurf[:, 0])
    yv = nodesurf[:, 1] / max(nodesurf[:, 1])

    sfrN, sfrM = fp.vectors(N, M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(type_sample, m, n, N, M, B, xv, yv, sfrM, sfrN, C1, RMS, out_pre)
    vertices = fp.make_rough(type_sample, z, nodesurf, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates a stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre+ str(j)  )
    #fp.refine_3Dmesh(type_sample, out_pre+str(j) , ns, alpha, ext_fem)

    return vertices, out_pre + str(j) + ".stl",


def make_atom_multilayered(
        type_sample,
        height_layer,
        pattern_layer,
        B,
        C1,
        RMS,
        N,
        M,
        length,
        height,
        width,
        ns,
        alpha,
        raw_stl,
        lattice_structure,
        lattice_parameter,
        material,
        orien_x0,
        orien_y0,
        orien_z0,
        out_pre,
        ext_fem,
        ext_ato,
):
    """
    Generates an atomic positions file for the multi_layer grain object.

    :param type_sample: The name of the sample
    :type type_sample: str
    :param pattern_layer: pattern of materials deposition
    :type pattern_layer: list
    :param height_layer: height of each layer
    :type height_layer: list
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Dimension of the Multi_layer
    :type length: float
    :param height: Dimension of the Multi_layer
    :type height: float
    :param width: Dimension of the Multi_layer
    :type width: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param lattice_structure: list which contains The lattice structure of crystals
    :type lattice_structure: list
    :param lattice_parameter: list which contains The lattice parameter of crystals in Angstrom
    :type lattice_parameter: list
    :param material: List of The chemical symbol of desired elements
    :type material: list
    :param orien_x: The orientation of crystals in the x direction, list of sublist
    :type orien_x: list
    :param orien_y: The orientation of crystals in the y direction, list of sublist
    :type orien_y: list
    :param orien_z: The orientation of crystals in the z direction, list of sublist
    :type orien_z: list
    :param out_pre: Prefix of output file
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list
    :param ext_ato: Atomic position file format list
    :type ext_ato: list

    :return: A Multi_layered NanoDevices
    """

    #Compute the height of the multi-layered object (height_pattern), using the height of each layer
    # global roughness_or_not_test
    height_pattern = 0
    for hl in range(len(pattern_layer)):
        index_layer = pattern_layer[hl]
        height_pattern = height_pattern + height_layer[index_layer]

    #Size check: height_pattern vs. user-defined size (Height, in the .json file) of the multi-layered object
    #Keep in mind that the pattern layer is periodically repeated : true_height = n_pattern x height_pattern
    n_pattern = int(height // height_pattern)
    if height % height_pattern != 0 :
        print("!!!WARNING!!!,To keep the periodicity, The height of the device will be truncated to this Height:" +str(n_pattern * height_pattern))

    #SECURITY ##############
    file_create = [out_pre+"_stat.txt"]
    #######################

    # CREATION OF ALL SUPERCELLS
    # 1 SUPERCELL PER MATERIAL, ALL WITH THE WHOLE SIZE OF THE SAMPLE
    try :
        #Initialise dimension of the supercell
        dim_x = length
        dim_y = width
        dim_z = n_pattern * height_pattern

        #Create supercells and register their file in a list
        list_supercell = []
        for atoms in range(len(material)):
            #dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x0[atoms], lattice_parameter[atoms], lattice_structure[atoms])
            #dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y0[atoms], lattice_parameter[atoms], lattice_structure[atoms])
            #dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z0[atoms], lattice_parameter[atoms], lattice_structure[atoms])
            #print("atoms : {}, dim_z {}, orien_z0[atoms] {}".format(atoms, dim_z, orien_z0[atoms]))

            #print("atoms / material : {} {}".format(atoms, len(material)))
            #print("len(lattice_structure[atoms]) : {}".format(len(lattice_structure[atoms])))
            #Here we generate blocks of atoms : mats_supercells.cfg
            if isinstance(lattice_structure[atoms], list) and len(lattice_structure[atoms]) > 1:
                # Binary random solid solution
                #print("if case")
                dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms][0])
                dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms][0])
                dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms][0])
                cmd = ["atomsk", "--create", str(lattice_structure[atoms][0]), str(*lattice_parameter[atoms]), str(material[atoms][0]),
                     "orient", str(orien_x), str(orien_y), str(orien_z),
                     "-duplicate", str(dup_x), str(dup_y), str(dup_z),
                     "-select", "random", str(lattice_structure[atoms][1])+"%", str(material[atoms][0]), "-substitute",
                     str(material[atoms][0]), str(material[atoms][1]),
                     "-center", "com", "mat" + str(atoms) + "_supercellm.cfg", "-v", "1"]
                print("Atomsk binary solution {}".format(cmd))
                subprocess.call(cmd)
                print("last file create is {}:".format("mat" + str(str(atoms)) + "_supercellm.cfg"))
            else:
                # Regular crystalline structure (as usually defined in Atomsk)
                #print("else case")
                dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms])
                dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms])
                dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms])
                #print("lattice_structure[atoms] : 0 = {}, 1 = {}, 2 = {}".format(lattice_structure[atoms][0], lattice_structure[atoms][1], lattice_structure[atoms][2]))
                cmd = ["atomsk", "--create", str(lattice_structure[atoms]), *lattice_parameter[atoms], *material[atoms],
                 "orient", str(orien_x), str(orien_y), str(orien_z),
                 "-duplicate", str(dup_x), str(dup_y), str(dup_z),
                 "-center", "com", "mat" + str(atoms) + "_supercellm.cfg", "-v", "1"]
                print("cmd : {}".format(cmd))
                subprocess.call(cmd)

            list_supercell.append("mat" + str(atoms) + "_supercellm.cfg")
            #list_supercell_out.append("toto" + str(atoms) + "_supercellm.cfg")

            # SECURITY ##############
            file_create.append("mat" + str(atoms) + "_supercellm.cfg")
            #######################

        # We deform each supercells to match their dimensions and preserve PBCs
        fp.av_length_and_strain(list_supercell,dim_z)

        # n is the index of a cell in a pattern of the Multi_layer, h is the initial height of the cell
        n, h = 0, 0

        # Initialise a list which will contain all patterns of the multi-layered object
        List_patterns = []
        for j in range(n_pattern):
            # Loop on the number of repetition of the main pattern (e.g., we want to repet 3x the pattern_layer=[0,1,2,1])
            if j == 0:
            # 1st pattern : the first slice is only half-height
                List_cells = []                     # list of material slices
                for n in range(len(pattern_layer)):
                    #In the j_th pattern, loop on each slice of material
                    #We define the geometry of the material, create an .stl file and remove exceeding atoms
                    print("#### SLICE n={}/{} in pattern j={}/{} under process...".format(n, len(pattern_layer)-1,j,n_pattern-1))
                    if n == 0:
                        # WARNING: the 1st slice of material (n=0) in the 1st pattern (j=0) has only a half-height
                        # the second-half will be pasted at the end of the sample to ensure periodicity

                        # Determine which material is concerned at the beginning
                        index_layer1 = pattern_layer[n]
                        # Use the Height of the material concerned at the beginning
                        height_layern = height_layer[index_layer1]
                        print("FEM_STL1, height_layern is {}, will be divided by 2 as n=j={}".format(height_layern, n))

                        vertices, FEM_STL1 = make_multi_layered(
                            type_sample,
                            index_layer1,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern / 2,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL1)
                        #file_create.append(out_pre + str(index_layer1) + ".msh")
                        #######################

                        #a = ""
                        #subprocess.call(["rm", out_pre + str(index_layer1) + ".msh"])
                        # Atomsk uses the .stl file to remove all atoms which are not in the position of the stl file
                        print("Atomsk run invert selection (top surface) : it cuts what is out of the STL")
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "cell" + str(n) + ".cfg",
                                "-v",
                                "1"
                            ]
                        )

                        # SECURITY ##############
                        #file_create.append("mat" + str(index_layer1) + "_outm.cfg")
                        #######################

                        # Register the first cell in the merge list
                        #subprocess.call(["mv", "mat" + str(index_layer1) + "_outm.cfg", "cell" + str(n) + ".cfg"])
                        #List_cells = List_cells + ["cell" + str(0) + ".cfg"]
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]

                        # SECURITY ##############
                        #file_create.append("cell" + str(0) + ".cfg")
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        h = 0 + height_layern / 2

                    elif n % 2 != 0:
                        # ODD SLICE (1, 3, 5, .... slice starts at 0) : they have the negative bottom roughness of the n-1 layer (no new .stl1) but a new top roughness (new .stl2)
                        # e.g., slice n=1 has the negative bottom roughness of slice n=0 (re-use of .stl1 file) but a new top roughness (new .stl2 file)
                        print("We are in the odd slice j={}, n={}".format(j,n))

                        # Determine which material is concerned
                        index_layer2 = pattern_layer[n]
                        # Use the Height of the material concerned
                        height_layern = height_layer[index_layer2]

                        print("FEM_STL2, height_layern is {}".format(height_layern))

                        vertices, FEM_STL2 = make_multi_layered(
                            type_sample,
                            index_layer2,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL2)
                        #######################

                        # Top roughness treatment:
                        print("Atomsk run invert selection (rough top surface - flat bottom) : it cuts what is out of the STL")
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer2) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-v",
                                "1"
                            ]
                        )
                        #subprocess.call(cmd)
                        print("top roughness is ok")

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer2) + "_outm.cfg")
                        #######################

                        # Bottom roughness treatment:
                        # use n-1 .stl file to generate the bottom roughness
                        #subprocess.call(
                        #print("C1 = {}, {} : eta = {}, {}, RMS = {}, {}".format(C1, type(C1), (B/2)-1, type(B), RMS, type(RMS)))

                        #if not C1:
                        #    print("C1 vide")
                        #if C1 is None:
                        #    print("C1 None")
                        #print("eta : {}, B {}".format((B/2)-1, B))

                        # Here we test if the multilayered systems has rough GBs or purely flat via eta, C1 and RMS, but they have to be defined
                        if 'C1' in locals() and C1:
                            print("C1 test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(C1) > 0.001
                        if 'RMS' in locals() and RMS:
                            print("RMS test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(RMS) > 0.01

                        #print("roughness_or_not_test : {}".format(roughness_or_not_test))
                        if roughness_or_not_test:
                            print("Atomsk run a regular selection (bottom surface) : it cuts what is in the previous STL (no invert)")
                            cmd=[
                                "atomsk",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-rmatom",
                                "select",
                                "matf_outm.cfg",
                                "-v",
                                "1"
                            ]
                            print("atomsk cmd = {}".format(cmd))
                            subprocess.call(cmd)
                        else:
                            print("Perfectly-flat multi-layer, we skip the bottom surface treatment for n=2k+1")
                            subprocess.call(['cp', "mat" + str(index_layer2) + "_outm.cfg", "matf_outm.cfg"])

                        # SECURITY ##############
                        file_create.append("matf_outm.cfg")
                        #######################

                        # Register the cell file
                        subprocess.call(["mv", "matf_outm.cfg", "cell" + str(n) + ".cfg"])
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        # Cleaning all undesirable file
                        subprocess.call(
                            [
                                "rm",
                                FEM_STL1,
                                "mat" + str(index_layer2) + "_outm.cfg",
                                out_pre + "_stat.txt",
                            ]
                        )
                        print("bottom roughness is ok")
                        h = h + height_layern

                    elif n % 2 == 0:
                        # Even SLICE (2, 4, 6,...) : they have the negative bottom roughness of the n-1 layer but a new top roughness
                        # e.g., slice n=2 the .stl2 file negative of n=1 for bottom roughness, but need a new top roughness called .stl1 again
                        print("We are in the even slice n={}".format(n))

                        # Top roughness treatment:
                        # Determine which material is concerned
                        index_layer1 = pattern_layer[n]
                        height_layern = height_layer[index_layer1]

                        # Use the Height of the material concerned
                        vertices, FEM_STL1 = make_multi_layered(
                            type_sample,
                            index_layer1,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL1)
                        file_create.append(out_pre + str(index_layer1) + ".msh")
                        #######################

                        subprocess.call(["rm", out_pre + str(index_layer1) + ".msh"])
                        a = str(n)

                        # Bottom roughness treatment (with fresh .stl1):
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-v",
                                "2",
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_supercellm" + a + ".cfg")
                        #######################

                        # Cleaning the STL of the previous cell
                        subprocess.call(["rm", FEM_STL2, ])

                        # Top roughness treatment (with fresh .stl1):
                        # Atomsk uses the .stl file to Remove all atoms which are not in the stl file
                        subprocess.call(
                                [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_outm.cfg",
                                "-v",
                                "2"
                                ]
                        )
                        #else:
                        #    print("Perfectly-flat multi-layer, we skip the surface treatment")
                        #    subprocess.call(['cp', "mat" + str(index_layer1) + "_supercellm" + a + ".cfg", "mat" + str(index_layer1) + "_outm.cfg"])

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_outm.cfg")
                        #######################

                        # Register the file in the cells file
                        subprocess.call(["mv", "mat" + str(index_layer1) + "_outm.cfg", "cell" + str(n) + ".cfg"])
                        subprocess.call(["rm", "mat" + str(index_layer1) + "_supercellm" + a + ".cfg", ])

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        FEM_STL2 = FEM_STL1
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]
                        h = h + height_layern


            elif j != 0:
                # For next patterns, we dont manage the half-height first slice of material

                List_cells = []
                for n in range(len(pattern_layer)):
                    print("#### SLICE n={}/{} in pattern j={}/{} under process...".format(n, len(pattern_layer)-1,j,n_pattern-1))

                    if n % 2 != 0:
                        # Determine which material is concerned
                        index_layer2 = pattern_layer[n]
                        # Use the Height of the material concerned
                        height_layern = height_layer[index_layer2]

                        vertices, FEM_STL2 = make_multi_layered(
                            type_sample,
                            index_layer2,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL2)
                        #file_create.append(out_pre + str(index_layer2) + ".msh")
                        #######################

                        # Atomsk uses the .stl file to remove all toms which are not in the STL file
                        # located cut-out : top surface rough but flat bottom surface that will be process afterwards using
                        # previous .stl
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer2) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-v",
                                "2"
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer2) + "_outm.cfg")
                        #######################

                        # Remove all atoms which are already in the previous cell
                        #if float(C1) > 0.01 and float(B) < 10.0 and float(RMS) > 0.01:
                        if 'C1' in locals() and C1:
                            print("C1 test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(C1) > 0.001
                        if 'RMS' in locals() and RMS:
                            print("RMS test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(RMS) > 0.01

                        #print("roughness_or_not_test : {}".format(roughness_or_not_test))
                        if roughness_or_not_test:
                            print(
                                "Atomsk run a regular selection (bottom surface) : it cuts what is in the previous STL (no invert)")

                            subprocess.call(
                                [
                                "atomsk",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-rmatom",
                                "select",
                                "matf_outm.cfg",
                                "-v",
                                "2"
                                ]
                             )
                        else:
                            print("Perfectly-flat multi-layer, we skip the bottom surface treatment to avoid Atomsk problem with empty region")
                            subprocess.call(['cp', "mat" + str(index_layer2) + "_outm.cfg", "matf_outm.cfg"])

                        # SECURITY ##############
                        file_create.append("matf_outm.cfg")
                        #######################

                        # Register the cell file
                        subprocess.call(["mv", "matf_outm.cfg", "cell" + str(n) + ".cfg"])
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        # Cleaning all undesirable file
                        subprocess.call(
                            [
                                "rm",
                                FEM_STL1,
                                "mat" + str(index_layer2) + "_outm.cfg",
                                out_pre + "_stat.txt",
                            ]
                        )
                        h = h + height_layern

                    elif n % 2 == 0:
                        # Determine which material is concerned
                        index_layer1 = pattern_layer[n]
                        height_layern = height_layer[index_layer1]
                        # Use the Height of the material concerned

                        vertices, FEM_STL1 = make_multi_layered(
                            type_sample,
                            index_layer1,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL1)
                        file_create.append(out_pre + str(index_layer1) + ".msh")
                        #######################

                        subprocess.call(["rm", out_pre + str(index_layer1) + ".msh"])
                        a = str(n)
                        # Remove atoms which are already in the previous cell
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-v",
                                "2"
                            ]
                            )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_supercellm" + a + ".cfg")
                        #######################

                        # Cleaning the STL of the previous cell
                        subprocess.call(["rm", FEM_STL2, ])

                        # Atomsk uses the .stl file to Remove all atoms which are not in the stl file
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_outm.cfg",
                                "-v",
                                "2"
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_outm.cfg")
                        #######################

                        # Register the file in the cells file
                        subprocess.call(["mv", "mat" + str(index_layer1) + "_outm.cfg", "cell" + str(n) + ".cfg"])
                        subprocess.call(["rm", "mat" + str(index_layer1) + "_supercellm" + a + ".cfg", ])

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        FEM_STL2 = FEM_STL1
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]
                        h = h + height_layern

            # MERGING OF THE MATERIAL SLICES FOR EACH PATTERN
            #Case with 1 cell/slice of material : register the cell/slice as the pattern
            if len(List_cells) == 1:
                subprocess.call(["mv", List_cells[0], "pattern" + str(j) + ".cfg"])

                # SECURITY ##############
                file_create.append("pattern" + str(j) + ".cfg")
                #######################

            #Case with many cells/slices : merge all cells of the pattern then register the final file in the pattern list
            else:
                for merge in range(len(List_cells) - 1):
                    if merge == 0:
                        subprocess.call(
                            ["atomsk", "--merge", "2", List_cells[0], List_cells[1], "celltot" + str(0) + ".cfg", "-v",
                                "2"])

                        # SECURITY ##############
                        file_create.append("celltot" + str(0) + ".cfg")
                        #######################



                    else:
                        subprocess.call(
                            ["atomsk", "--merge", "2", "celltot" + str(merge - 1) + ".cfg", List_cells[merge + 1],
                                "celltot" + str(merge) + ".cfg", "-v", "2"])
                        #Cleaning
                        subprocess.call(["rm", "celltot" + str(merge - 1) + ".cfg", ])

                        # SECURITY ##############
                        file_create.append( "celltot" + str(merge) + ".cfg")
                        #######################

                subprocess.call(
                    ["mv", "celltot" + str(len(List_cells) - 1 - 1) + ".cfg", "pattern" + str(j) + ".cfg"])

                #SECURITY ##############
                file_create.append("pattern" + str(j) + ".cfg")
                #######################


            subprocess.call(["rm", out_pre+"_stat.txt"])
            List_patterns.append("pattern" + str(j) + ".cfg")

            for m in range(len(List_cells)):
                # Cleaning all cells .cfg
                subprocess.call(["rm",List_cells[m],])

        # MERGING OF THE PATTERNS
        # Case with 1 pattern :
        if len(List_patterns) == 1:
            subprocess.call(["mv", List_patterns[0], out_pre+"0.cfg"])
        # Case with many patterns : Merge all patterns together
        else:
            for merge in range(len(List_patterns) - 1):
                if merge == 0:
                    subprocess.call(
                        ["atomsk", "--merge", "2", List_patterns[0], List_patterns[1], "patterntot" + str(0) + ".cfg", "-v","2"])

                    # SECURITY ##############
                    file_create.append("patterntot" + str(0) + ".cfg")
                    #######################

                else:
                    subprocess.call(
                    ["atomsk", "--merge", "2", "patterntot" + str(merge - 1) + ".cfg", List_patterns[merge + 1],
                    "patterntot" + str(merge) + ".cfg", "-v", "2"])
                    #Cleaning
                    subprocess.call(["rm", "patterntot" + str(merge - 1) + ".cfg", ])

                    # SECURITY ##############
                    file_create.append("patterntot" + str(merge) + ".cfg")
                    #######################

            subprocess.call(["mv", "patterntot" + str(len(List_patterns) - 1 - 1) + ".cfg", out_pre+"0.cfg"])

        # SECURITY ##############
        file_create.append(out_pre+"0.cfg")
        #######################

        # ADD OF THE ENDING-SAMPLE HALF-HEIGHT OF THE FIRST SLICE OF MATERIAL (PBCs)
        #Complete the final empty part with the first material used to keep the vertical periodicity
        vertices, END = make_box("box", B, C1, RMS, N, M, length+50, h-height_layern, width+50, ns, alpha, raw_stl, "final",ext_fem)
        subprocess.call(["atomsk", "mat"+str(pattern_layer[0])+"_supercellm.cfg", "-select", "stl", FEM_STL2, "-rmatom", "select", "end0.cfg", "-v", "2"])
        subprocess.call(["atomsk", "end0.cfg", "-select", "stl", END, "-rmatom", "select", "final0.cfg", "-v", "2"])
        subprocess.call(["atomsk", "--merge", "2", out_pre+"0.cfg", "final0.cfg", out_pre+".cfg", "-v","2"])  # merge the end to the object create

        # SECURITY ##############
        file_create.append("end0.cfg")
        file_create.append( END)
        file_create.append("final0.cfg")
        file_create.append(out_pre+".cfg")
        file_create.append("final_stat.txt")
        file_create.append("final_stat.msh")
        #######################
    
        #Create the lmp file
        for e in ext_ato:
            if e != "cfg":
                subprocess.call(["atomsk", out_pre+".cfg", out_pre + "." + e, "-v", "2"])

        #Remove all files
        subprocess.call(["rm", "patterntot" + str(len(List_patterns)-1-1) + ".cfg", "final0.cfg", out_pre+".cfg",out_pre+"0.cfg",out_pre+"1.cfg", END, "end0.cfg","final.msh", "final_stat.txt",])

        #Clean all patterns files
        for m in range(len(List_patterns)):
            # Cleaning all cells .cfg
            subprocess.call(["rm",List_patterns[m]])

        #Clean the rest of files :
        subprocess.call(["rm", FEM_STL2,out_pre+"_stat.txt"])
        for suppr in range(len(list_supercell)):
            # Cleaning all cells .cfg
            subprocess.call(["rm",list_supercell[suppr]])

        subprocess.call(["clear", ])
        print("JOB DONE!" + "  File name: " + out_pre + ".lmp")

    except Exception as ex:
        import traceback
        print(f"ERROR: {ex}")
        print("Detailed error traceback:")
        traceback.print_exc()
        #Supprime tous les fichiers créés depuis le début
        for file in file_create:
            subprocess.call(["rm", file])
            print(f"File deleted: {file}")
        print("Cleaning File Done")
