# ---------------------------------------------------------------------------
# Title: SAMPLE CLASS
# Authors: Jonathan Amodeo, Hugo Iteney, Javier Gonzalez, Jennifer Izaguirre, Christophe Le Bourlot, Thomas Cadart
# Date: June 01, 2022
#
# The SAMPLE class is responsible for generating the desired object shape (nanowire, slab, sphere, etc.)
# and creating the appropriate file type.
# The MAKE_STL function generates an .stl file of the shape, which is useful for FEM simulations.
# In this method, the shape is created based on user-defined parameters obtained from the PARAM class.
# The MAKE_ATOM function creates an .lmp file, which requires the .stl file generated by MAKE_STL.
# The parameters for generating the .lmp file are determined by the user's input.
# ---------------------------------------------------------------------------
#from tqdm import tqdm
import json
import os
import shutil
import tempfile
import time
import subprocess

import numpy as np
from src import Func_pyrough as fp


class Sample:
    def __init__(self, type_sample):
        self.sample = type_sample

    def make_stl(self, param, out_pre):
        """
        Creates an stl file based on the parameters chosen by the user. Based on the type of sample
        entered, the code will sort through the options of type of samples and if true then the
        code under the type of sample will be executed. The type of sample affects the type of stl
        file returned. The code executed requires the parameters to create the object stl and to
        apply surface roughness onto the object. ...; In continuation will add that a separate
        files will be stored if they want to redo the code.

        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        :param out_pre: Prefix of the output files
        :type out_pre: str

        :returns: List of nodes and stl file name
        """
        if param.type_S == "cwire":
            vertices, _, stl, rot_stl = make_cwire(param, out_pre)
        elif param.type_S == "box":
            vertices, _, stl, rot_stl = make_box(param, out_pre)
        elif param.type_S == "sphere":
            vertices, _, stl, rot_stl = make_sphere(param, out_pre)
        elif param.type_S == "fwire":
            vertices, _, stl, rot_stl = make_fwire(param, out_pre)
        elif param.type_S == "fpillar":
            vertices, _, stl, rot_stl = make_fpillar(param, out_pre)
        elif param.type_S == "cpillar":
            vertices, _, stl, rot_stl = make_cpillar(param, out_pre)
        elif param.type_S == "wulff":
            vertices, _, stl, rot_stl = make_wulff(param, out_pre)
        elif param.type_S == "cube":
            vertices, _, stl, rot_stl = make_cube(param, out_pre)
        elif param.type_S == "lattice":
            vertices, _, stl, rot_stl = make_lattice(param, out_pre)
        else:
            raise ValueError("No valid sample type found in the JSON file.")
        return vertices, stl, rot_stl

    def make_atom(
            self,
            STL,
            param,
            vertices,
            out_pre):
        """
        Creates an atom position file sample_with_atoms.lmp. This requires a .stl file with rough surfaces
        used as a stencil over a larger block of atoms from which out-of-the-mesh atoms are removed


        :param STL: The stl file with an object that has surface roughness applied to it
        :type STL: str
        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        :param vertices: List of nodes
        :type vertices: array
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """

        dim_x = max(vertices[:, 0]) - min(vertices[:, 0])
        dim_y = max(vertices[:, 1]) - min(vertices[:, 1])
        dim_z = max(vertices[:, 2]) - min(vertices[:, 2])

        dis_x, dup_x, orien_x = fp.duplicate(dim_x, param.orien_x[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])
        dis_y, dup_y, orien_y = fp.duplicate(dim_y, param.orien_y[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])
        dis_z, dup_z, orien_z = fp.duplicate(dim_z, param.orien_z[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])

        # Here we create a large block of atoms material_supercell.lmp
        subprocess.call([
            "atomsk", "--create",
            param.lattice_structure[0],
            *param.lattice_parameter[0],
            *param.material[0],
            "orient", orien_x, orien_y, orien_z,
            "-duplicate", dup_x, dup_y, dup_z,
            "material_supercell.lmp", "-v", "2",
        ])

        # Then the STL file is used as a stencil over material_supercell.lmp and extra atoms are removed
        subprocess.call([
            "atomsk", "material_supercell.lmp",
            "-select", "stl", "center", STL,
            "-select", "invert", "-rmatom", "select",
            out_pre + ".lmp",
            "-v", "2",
        ])

        fp.remove_file("material_supercell.lmp")

        fp.rebox(out_pre + ".lmp", 0.001)

        # Euler rotation
        fp.lmp_rotate_euler(out_pre + ".lmp", out_pre + "_rot.lmp", param.angles2, order='zyx')

        fp.rebox(out_pre + "_rot.lmp", 0.001)

        fp.move_file(out_pre + "_rot.lmp", out_pre + ".lmp")

        if param.ext_ato != ['lmp']:
            cmd = ["atomsk",
                   out_pre + ".lmp",
                   " ".join([x for x in param.ext_ato[0:] if x != "lmp"])
                   ]
            subprocess.call(cmd)

    def make_precipitate(
            self,
            STL,
            param
    ):
        """
        Creates an atom position file sample_with_atoms.lmp. This requires a .stl file with rough surfaces
        used as a stencil over a larger block of atoms from which out-of-the-mesh atoms are removed

        :param STL: The stl file with an object that has surface roughness applied to it
        :type STL: str
        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        """

        dis_x, dup_x, orien_x = fp.duplicate(param.length_x2, param.orien_x[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])
        dis_y, dup_y, orien_y = fp.duplicate(param.length_y2, param.orien_y[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])
        dis_z, dup_z, orien_z = fp.duplicate(param.length_z2, param.orien_z[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])

        cmd = [
            "atomsk",
            "--create",
            param.lattice_structure[0],
            *param.lattice_parameter[0],
            *param.material[0],
            "orient",
            orien_x,
            orien_y,
            orien_z,
            "-duplicate",
            dup_x,
            dup_y,
            dup_z,
            "precipitate_supercell.xyz",
            "-v ",
            "2",
        ]

        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over precipitate_supercell.lmp and extra atoms are removed
        cmd = [
            "atomsk",
            "precipitate_supercell.xyz",
            "-select",
            "stl",
            "center",
            STL,
            "-select",
            "invert",
            "-rmatom",
            "select",
            "precipitate.xyz",
            "-v",
            "2",
        ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        temp_file = "precipitate_supercell.xyz"
        fp.remove_file(temp_file)

        # Precipitate rotation : Euler rotation
        fp.xyz_rotate_euler("precipitate.xyz", "precipitate_rot.xyz", param.angles2, order='zyx')
        fp.move_file("precipitate_rot.xyz", "precipitate.xyz")
        fp.remove_file(STL)

    def make_atom_matrix(
            self,
            ROTSTL,
            param
    ):
        """
        Creates an orthogonal matrix made of atoms.

        :param ROTSTL: The stl file with an object that has surface roughness applied to it and rotated with Euler angles
        :type ROTSTL: str
        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        """

        dis_x, dup_x, orien_x = fp.duplicate(param.length_x2, param.orien_x2, param.lattice_parameter2,
                                             param.lattice_structure2)
        dis_y, dup_y, orien_y = fp.duplicate(param.length_y2, param.orien_y2, param.lattice_parameter2,
                                             param.lattice_structure2)
        dis_z, dup_z, orien_z = fp.duplicate(param.length_z2, param.orien_z2, param.lattice_parameter2,
                                             param.lattice_structure2)

        # Creation of a matrix of atoms i.e., a large orthogonal block of atoms
        cmd = [
            "atomsk",
            "--create",
            param.lattice_structure2,
            *param.lattice_parameter2,
            *param.material2,
            "orient",
            orien_x,
            orien_y,
            orien_z,
            "-duplicate",
            dup_x,
            dup_y,
            dup_z,
            "matrix.lmp",
            "-v",
            "2",
        ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over material_supercell.lmp and extra atoms are removed
        if param.precpos == 'center':
            cmd = [
                "atomsk",
                "matrix.lmp",
                "-select",
                "stl",
                "center",
                ROTSTL,
                "-rmatom",
                "select",
                "matrix_w_inprint.lmp",
                "-v",
                "2",
            ]

            # print("Atomsk call:", " ".join(map(str, cmd)))
            subprocess.call(cmd)
        else:
            fp.atomsk_select_stl_local_cutin("matrix.lmp", ROTSTL, "matrix_w_inprint.lmp", param.precpos)

        fp.remove_file("matrix.lmp")
        fp.remove_file(ROTSTL)

    def put_prec_in_matrix(
            self,
            out_pre,
            ext_ato
    ):
        """
        Introduce a cube/sphere/wulff precipitate into a matrix

        :param out_pre_matrix: Matrix sample
        :type out_pre_matrix: str
        :param STL: The stl file with an object that has surface roughness
        :type STL: str
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """
        # This atomsk call use the same STL file than for block 1 to carve out part of out_pre_matrix into mat2_out.xyz
        # As using thee same STL file but with the invert option, mat2_out.xyz is the negative of mat1_out.xyz
        cmd = [
            "atomsk",
            "--merge",
            "2",
            #"matrix_w_inprint.xyz",
            "matrix_w_inprint.lmp",
            "precipitate.xyz",
            out_pre + ".xyz",
            "-v",
            "2",
        ]
        print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        subprocess.call(["atomsk", out_pre + ".xyz", out_pre + ".lmp"])

        for e in ext_ato:
            if e != "lmp":
                subprocess.call(["atomsk", out_pre + ".lmp", out_pre + "." + e, "-v", "2"])

        #subprocess.call(["rm", "matrix.xyz", "precipitate.xyz", out_pre + ".xyz"])


def make_cwire(param, out_pre):
    """
    Creates an stl file of a rough wire

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str
    
    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, 0)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array file
    # from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, 0, 0)

    # convert to cylindrics coordinates (Rho Theta Z nodenumb)
    cy_nodesurf = np.array(
        [
            fp.rho(nodesurf[:, 0], nodesurf[:, 1]),
            fp.theta(nodesurf[:, 0], nodesurf[:, 1]),
            nodesurf[:, 2],
            nodesurf[:, 3],
        ]
    ).T

    cy_nodesurf = cy_nodesurf[np.lexsort((cy_nodesurf[:, 1], cy_nodesurf[:, 2]))]

    # creating X and Y vector (Connection matrix size) going to make one line code
    xv = (cy_nodesurf[:, 1] / max(cy_nodesurf[:, 1]) + 1) / 2
    yv = (cy_nodesurf[:, 2] / max(cy_nodesurf[:, 2]) + 1) / 2

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, cy_nodesurf, vertices, 0)

    # gets ride of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates an stl file of the cylinder with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_box(param, out_pre):
    """
    Creates an stl file of a rough box

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, param.width, param.length, param.height, 0, param.ns, 0)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, 0, 0)
    nodesurf = nodesurf[np.lexsort((nodesurf[:, 0], nodesurf[:, 1]))]

    xv = nodesurf[:, 0] / max(nodesurf[:, 0])
    yv = nodesurf[:, 1] / max(nodesurf[:, 1])

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, nodesurf, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates an stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_sphere(param, out_pre):
    """
    Creates an stl file of a rough sphere

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, 0, 0, param.radius, param.ns, 0)
    nbPoint = len(vertices)

    r = np.zeros(nbPoint)
    x, y, z, t = fp.coord_sphere(vertices)
    vert_phi_theta = fp.vertex_tp(x, y, t, z)

    thetaa = fp.theta(y, x)
    phii = fp.phi(t, z)

    # creates the displacement values of the nodes on the surface of the sphere
    r = fp.rough_matrix_sphere(nbPoint, param.B, thetaa, phii, vert_phi_theta, r)

    # creates a new matrix with x, y, z in cartesian coordinates
    C2 = 1.0 / nbPoint / param.N / 2.0
    new_vertex = fp.coord_cart_sphere(param.C1, C2, r, vertices, t, z, y, x)

    # creates an stl file of the sphere with roughness on the surface
    fp.stl_file(new_vertex, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_fwire(param, out_pre):
    """
    Creates an stl file of a rough faceted wire

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    points, angles = fp.base(param.radius, param.nfaces)

    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, points)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(
        param.type_S,
        vertices,
        nodenumber,
        points,
        0,
    )
    cy_nodesurf = fp.cart2cyl(nodesurf)
    sorted_cy_nodesurf = cy_nodesurf[np.lexsort((cy_nodesurf[:, 1], cy_nodesurf[:, 2]))]
    nodesurf = fp.cyl2cart(sorted_cy_nodesurf)

    Z = len(np.where(sorted_cy_nodesurf[:, 2] == 0)[0])
    T = len(np.unique(sorted_cy_nodesurf[:, 2]))
    xv = np.linspace(0, 1, Z)
    yv = np.linspace(0, 1, T)

    xv, yv = np.meshgrid(xv, yv)

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, nodesurf, vertices, angles)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]
    vertices = fp.align_f(vertices, angles)

    # creates an stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_wulff(param, out_pre):
    """
    Creates an stl file of a rough Wulff-shaped nanoparticle

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix for output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    obj_points, obj_faces = fp.make_obj(
        param.surfaces,
        param.energies,
        param.n_at,
        param.lattice_structure[0],
        param.lattice_parameter[0],
        param.material[0],
        param.orien_x[0],
        param.orien_z[0],
        out_pre,
    )
    vertices, faces = fp.read_stl_wulff(param.raw_stl, obj_points, obj_faces, param.ns)

    fp.remove_file(out_pre + ".obj")
    list_n = fp.faces_normals(obj_points, obj_faces)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, obj_points, obj_faces)

    node_edge, node_corner = fp.node_corner(nodesurf)

    vertices = fp.make_rough_wulff(
        vertices, param.B, param.C1, param.RMS, param.N, param.M, nodesurf, node_edge, node_corner, list_n
    )

    vertices = vertices[:, :3]

    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_cube(param, out_pre):
    """
    Creates an stl file of a cubic NP

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """

    obj_points, obj_faces = fp.cube_faces(param.width, param.length, param.height)
    list_n = fp.faces_normals(obj_points, obj_faces)

    vertices, faces = fp.cube(param.width, param.length, param.height, param.ns)
    vertices, nodenumber = fp.node_indexing(vertices)

    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, obj_points, obj_faces)
    node_edge, node_corner = fp.node_corner(nodesurf)

    vertices = fp.make_rough_wulff(
        vertices, param.B, param.C1, param.RMS, param.N, param.M,
        nodesurf, node_edge, node_corner, list_n
    )

    vertices = fp.center_3d_dataset(vertices[:, :3])

    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_lattice(param, out_pre):
    """
    Creates an stl file of a lattice structure

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    try:
        import manifold3d as manifold
    except ImportError:
        raise ImportError("manifold3d library is not installed. Please install it with: pip install manifold3d")

    try:
        import trimesh
    except ImportError:
        raise ImportError("trimesh library is not installed. Please install it with: pip install trimesh")

    try:
        import pymeshlab
    except ImportError:
        raise ImportError("pymeshlab library is not installed. Please install it with: pip install pymeshlab")

    try:
        from pyLatticeDSO.src.pyLatticeDesign.lattice import Lattice
    except ImportError:
        raise ImportError("pyLatticeDSO library is not installed as submodule."
                          "Please install it to use this feature. See documentation.")

    def numpy_to_manifold(vertices, faces):
        """
        Converts numpy arrays of vertices and faces into a manifold3d Manifold object.
        This includes repairing the mesh to ensure it is watertight and suitable for boolean operations.
        """
        tmp = trimesh.Trimesh(vertices=vertices, faces=faces)
        tmp.remove_unreferenced_vertices()
        tmp.fix_normals()
        trimesh.repair.fix_winding(tmp)
        trimesh.repair.fix_normals(tmp)
        trimesh.repair.fill_holes(tmp)

        return manifold.Manifold(
            mesh=manifold.Mesh(
                vert_properties=np.array(tmp.vertices, dtype=np.float32),
                tri_verts=np.array(tmp.faces, dtype=np.uint32)
            )
        )

    # Lattice object creation
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as tmp:
        json.dump(param.geometry_lattice, tmp, indent=2)
        tmp_path = tmp.name

    try:
        lattice_object = Lattice(tmp_path)
    finally:
        fp.remove_file(tmp_path)

    param_type_S_backup = param.type_S
    all_manifolds = []

    # Generate the rough wire mesh for each beam
    if lattice_object.beams is None or len(lattice_object.beams) == 0:
        raise ValueError("No beams found in the lattice structure. Please check the input JSON file.")
    for beam in lattice_object.beams:
        p1 = np.array(beam.point1.coordinates)
        p2 = np.array(beam.point2.coordinates)
        radius = beam.initial_radius if getattr(beam, "initial_radius", None) is not None else beam.radius
        param.radius = radius
        param.length = beam.length
        if param.beam_type == "cwire":
            param.type_S = "cwire"
            vertices, faces, _, _ = make_cwire(param, out_pre)
        elif param.beam_type == "fwire":
            param.type_S = "fwire"
            vertices, faces, _, _ = make_fwire(param, out_pre)
        else:
            raise ValueError("No valid beam type found in the JSON file.")

        # Positioning the wire at the correct location
        direction = p2 - p1
        R = fp.rotation_from_z_axis(direction)
        vertices = fp.apply_rigid_transform(vertices, R, np.zeros(3))
        vertices += p1

        beam_manifold = numpy_to_manifold(vertices, faces)
        all_manifolds.append(beam_manifold)

    # Perform boolean union of all beam manifolds
    union_manifold = all_manifolds[0]
    for m in all_manifolds[1:]:
        union_manifold = union_manifold + m

    if param.trim_boundary_beams:
        x0, y0, z0 = lattice_object.x_min, lattice_object.y_min, lattice_object.z_min
        dx, dy, dz = (lattice_object.x_max - x0,
                      lattice_object.y_max - y0,
                      lattice_object.z_max - z0)

        # Generate a rough box mesh that will be used to trim the beams at the lattice boundaries
        obj_points, obj_faces = fp.cube_faces(dy, dx, dz)
        list_n = fp.faces_normals(obj_points, obj_faces)

        box_vertices, box_faces = fp.read_stl("cube", param.raw_stl, dy, dx, dz, 0, param.ns, 0)
        box_vertices, box_nodenumber = fp.node_indexing(box_vertices)

        nodesurf = fp.node_surface("cube", box_vertices, box_nodenumber, obj_points, obj_faces)
        node_edge, node_corner = fp.node_corner(nodesurf)

        C1_box = param.cube_trimmer_param.get("C1", param.C1)
        eta_box = param.cube_trimmer_param.get("eta", param.eta)
        B_box = 2 * (1 + eta_box)
        RMS_box = param.cube_trimmer_param.get("RMS", param.RMS)
        N_box = param.cube_trimmer_param.get("N", param.N)
        M_box = param.cube_trimmer_param.get("M", param.M)
        box_vertices = fp.make_rough_wulff(
            box_vertices, B_box, C1_box, RMS_box, N_box, M_box,
            nodesurf, node_edge, node_corner, list_n
        )

        # Translate the box to the correct position
        box_vertices = box_vertices[:, :3]
        box_vertices += np.array([x0, y0, z0])

        rough_box_trimesh = trimesh.Trimesh(vertices=box_vertices, faces=box_faces)
        rough_box_trimesh.remove_unreferenced_vertices()
        rough_box_trimesh.fix_normals()
        trimesh.repair.fix_winding(rough_box_trimesh)
        trimesh.repair.fill_holes(rough_box_trimesh)
        rough_box_trimesh.export(out_pre + "_rough_box.stl")

        rough_box = manifold.Manifold(
            mesh=manifold.Mesh(
                vert_properties=np.array(rough_box_trimesh.vertices, dtype=np.float32),
                tri_verts=np.array(rough_box_trimesh.faces, dtype=np.uint32)
            )
        )

        union_manifold = union_manifold ^ rough_box
        print("====== > Rough bounding box applied.")

        if union_manifold.is_empty():
            raise ValueError(
                f"Empty intersection !\n"
                f"Rough box bounds: {rough_box_trimesh.bounds}\n"
                f"Lattice: x=[{x0},{x0 + dx}], y=[{y0},{y0 + dy}], z=[{z0},{z0 + dz}]"
            )

    # Convert the final manifold back to a mesh and export as STL
    mesh = union_manifold.to_mesh()

    tmp = trimesh.Trimesh(
        vertices=mesh.vert_properties,
        faces=mesh.tri_verts
    )

    # name_mesh = out_pre + "temp.stl"
    # tmp.export(name_mesh)

    # Determine target edge length for remeshing based on the average edge length of the current mesh
    edge_lengths = tmp.edges_unique_length
    target_len = float(np.mean(edge_lengths))

    # print(f"Target edge length: {target_len:.4f}")

    bbox_diagonal = np.linalg.norm(tmp.bounds[1] - tmp.bounds[0])
    target_percentage = (target_len / bbox_diagonal) * 100

    # print(f"Target edge length: {target_len:.4f}")
    # print(f"Bbox diagonal: {bbox_diagonal:.4f}")
    # print(f"Target percentage: {target_percentage:.4f}%")
    target_percentage /= 2.0

    # Remesh the mesh using PyMeshLab to achieve a more uniform distribution of vertices
    ms = pymeshlab.MeshSet()
    ms.add_mesh(pymeshlab.Mesh(
        vertex_matrix=tmp.vertices,
        face_matrix=tmp.faces
    ))

    # Remesh the mesh using isotropic explicit remeshing to achieve a more uniform distribution of vertices
    ms.meshing_isotropic_explicit_remeshing(
        targetlen=pymeshlab.PercentageValue(target_percentage),
        iterations=5
    )

    remeshed = ms.current_mesh()
    final_mesh = trimesh.Trimesh(vertices=remeshed.vertex_matrix(), faces=remeshed.face_matrix())

    name_mesh = out_pre + ".stl"
    final_mesh.export(name_mesh)

    # Reset param.type_S to its original value for downstream processing
    param.type_S = param_type_S_backup

    # fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return mesh.vert_properties, mesh.tri_verts, out_pre + ".stl", out_pre + "_rot.stl"


def make_atom_grain(
        STL,
        param,
        vertices,
        out_pre):
    """
    Generates an atomic positions file for the grain object.

    :param STL: The stl file with an object that has surface roughness applied to it
    :type STL: str
    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param vertices: List of nodes
    :type vertices: array
    :param out_pre: Prefix of output file
    :type out_pre: str

    :return: None, but generates an atomic positions file for the grain object in the same directory as the script
    with the name out_pre.lmp
    """


    dim_x = max(vertices[:, 0]) - min(vertices[:, 0])
    dim_y = max(vertices[:, 1]) - min(vertices[:, 1])
    dim_z = max(vertices[:, 2]) - min(vertices[:, 2])

    #print("stl dim : {} {} {}".format(dim_x, dim_y, dim_z))

    supercell_files = []

    for i in range(len(param.material)):
        dis_x, dup_x, orien_x = fp.duplicate(dim_x, param.orien_x[i], param.lattice_parameter[i], param.lattice_structure[i])
        dis_y, dup_y, orien_y = fp.duplicate(dim_y, param.orien_y[i], param.lattice_parameter[i], param.lattice_structure[i])
        dis_z, dup_z, orien_z = fp.duplicate(2 * dim_z, param.orien_z[i], param.lattice_parameter[i], param.lattice_structure[i])

        outfile = f"mat{i + 1}_supercell.cfg"
        subprocess.call([
            "atomsk", "--create",
            param.lattice_structure[i],
            *param.lattice_parameter[i],
            *param.material[i],
            "orient", orien_x, orien_y, orien_z,
            "-duplicate", dup_x, dup_y, dup_z,
            "-center", "com",
            outfile, "-v", "2",
        ])
        supercell_files.append(outfile)

    # Deform mat2 to match mat1 (arbitrary)
    #for i in range(1, len(supercell_files)):
    fp.strain_file1_to_file2(supercell_files[1], supercell_files[0])

    # Rescale stl file to newly deformed materials (else miscut can appear)
    #fp.rescale_stl_xy_to_cfg(STL, supercell_files[0])

    # Carve mat1 with STL (keep inside)
    subprocess.call([
        "atomsk", supercell_files[0],
        "-select", "stl", STL,
        "-rmatom", "select", "mat1_out.cfg", "-v", "2",
    ])

    # Carve mat2 with STL inverted (keep outside)
    subprocess.call([
        "atomsk", supercell_files[1],
        "-select", "stl", STL,
        "-select", "invert",
        "-rmatom", "select", "mat2_out.cfg", "-v", "2",
    ])

    # Shifting (optional)
    for i in range(len(param.material)):
        if any(float(value) != 0.0 for value in param.shift[i]):
            print("Shift atoms processing..")
            file = f"mat{i + 1}_out.cfg"
            subprocess.call([
                "atomsk",
                file,
                 "-shift", param.shift[i][0], param.shift[i][1], param.shift[i][2],
                "temp.cfg", "-v", "2",
            ])
            os.rename("temp.cfg", file)

    # Merge
    subprocess.call(["atomsk", "--merge", "2", "mat1_out.cfg", "mat2_out.cfg", "temp2.cfg", "-v", "2"])

    # Rebox (if shift)
    for i in range(len(param.material)):
        if any(float(value) != 0.0 for value in param.shift[i]):
            print("After-shift rebox processing..")
            fp.rebox_w_atomsk("temp2.cfg", "temp2_rebox.cfg")
            os.rename("temp2_rebox.cfg", "temp2.cfg")

    # Outfiles
    for e in param.ext_ato:
        subprocess.call(["atomsk", "temp2.cfg", out_pre + "." + e, "-v", "2"])

    # Cleaning
    for f in supercell_files + ["mat1_out.cfg", "mat2_out.cfg", "temp2.cfg"]:
        fp.remove_file(f)


def make_fpillar(param, out_pre):
    """
    Creates an stl file of a rough faceted pillar

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name for a Faceted Pillar
    """
    # create the base of the faceted Pillar
    points, anglesfac = fp.base(param.radius, param.nfaces)

    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, points)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumber which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    # nodesurf 1 is the faceted wire surface, and nodesurf2 is the topside surface
    nodesurf1 = fp.node_surface("fwire", vertices, nodenumber, points, 0)
    nodesurf2 = fp.node_surface("box", vertices, nodenumber, 0, 0)

    # Save the index of nodes which are on the edge of the pillar
    nodesurftot = [nodesurf1] + [nodesurf2]
    node_edge, node_corner = fp.node_corner(nodesurftot)

    # convert to cylindrics coordinates (Rho Theta Z nodenumber)
    cy_nodesurf1 = fp.cart2cyl(nodesurf1)
    sorted_cy_nodesurf1 = cy_nodesurf1[np.lexsort((cy_nodesurf1[:, 1], cy_nodesurf1[:, 2]))]
    nodesurf1 = fp.cyl2cart(sorted_cy_nodesurf1)

    Z = len(np.where(sorted_cy_nodesurf1[:, 2] == 0)[0])
    T = len(np.unique(sorted_cy_nodesurf1[:, 2]))

    xv1 = np.linspace(0, 1, Z)
    yv1 = np.linspace(0, 1, T)
    xv1, yv1 = np.meshgrid(xv1, yv1)
    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m1, n1 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    xv2 = nodesurf2[:, 0] / max(nodesurf2[:, 0])
    yv2 = nodesurf2[:, 1] / max(nodesurf2[:, 1])
    m2, n2 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # Array these represent the roughness on the surface
    z1 = fp.random_surf2("fwire", m1, n1, param.N, param.M, param.B1, xv1, yv1, sfrM, sfrN, param.C1, param.RMS1, out_pre)
    z2 = fp.random_surf2("box", m2, n2, param.N, param.M, param.B2, xv2, yv2, sfrM, sfrN, param.C2, param.RMS2, out_pre)

    # Displace nodes to make surfaces rough, nodes on the edge are displace 2 times so these displacement should be
    # normalised
    vertices = fp.make_rough_pillar(param.type_S, z1, z2, nodesurf1, nodesurf2, node_edge, vertices, anglesfac)
    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    vertices = fp.align_f(vertices, anglesfac)
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_cpillar(
        param,
        out_pre,
):
    """
    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name for a circular Pillar
    """
    if len(param.eta == 1):
        B = [param.B, param.B]
        C1 = [param.C1, param.C1]
        RMS = [param.RMS, param.RMS]
    else:
        B = [param.B[0], param.B[1]]
        C1 = [param.C1[0], param.C1[1]]
        RMS = [param.RMS[0], param.RMS[1]]

    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, 0)

    # Creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumber which is an array file
    # from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # Nodes at the surface of the object. These nodes will have the surface roughness applied to it
    # nodesurf 1 is the wire surface, and nodesurf2 is the topside surface
    nodesurf1 = fp.node_surface("cwire", vertices, nodenumber, 0, 0)
    nodesurf2 = fp.node_surface("box", vertices, nodenumber, 0, 0)

    # Getting the index of nodes on the edge
    nodesurftot = [nodesurf1] + [nodesurf2]
    node_edge, node_corner = fp.node_corner(nodesurftot)

    # Convert to cylindrics coordinates (Rho Theta Z nodenumber)
    cy_nodesurf1 = np.array(
        [
            fp.rho(nodesurf1[:, 0], nodesurf1[:, 1]),
            fp.theta(nodesurf1[:, 0], nodesurf1[:, 1]),
            nodesurf1[:, 2],
            nodesurf1[:, 3],
        ]
    ).T

    cy_nodesurf1 = cy_nodesurf1[np.lexsort((cy_nodesurf1[:, 1], cy_nodesurf1[:, 2]))]

    # Creating X and Y vector (Connection matrix size) going to make one line code
    xv1 = (cy_nodesurf1[:, 1] / max(cy_nodesurf1[:, 1]) + 1) / 2
    yv1 = (cy_nodesurf1[:, 2] / max(cy_nodesurf1[:, 2]) + 1) / 2

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m1, n1 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    xv2 = nodesurf2[:, 0] / max(nodesurf2[:, 0])
    yv2 = nodesurf2[:, 1] / max(nodesurf2[:, 1])
    m2, n2 = fp.random_numbers(sfrN, sfrM)

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # Array these represent the roughness on the surface
    z1 = fp.random_surf2("cwire", m1, n1, param.N, param.M, B[0], xv1, yv1, sfrM, sfrN, C1[0], RMS[0], out_pre)
    z2 = fp.random_surf2("box", m2, n2, param.N, param.M, B[1], xv2, yv2, sfrM, sfrN, C1[1], RMS[1], out_pre)

    vertices = fp.make_rough_pillar(param.type_S, z1, z2, cy_nodesurf1, nodesurf2, node_edge, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates a stl file of the cylinder with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_multi_layered(param, out_pre, index_layer, h, height):
    """
    Creates an stl file of a rough box slice used to build one layer of a multi_layered sample.

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files (also the roughness stat file, appended to at every call)
    :type out_pre: str
    :param index_layer: Index of the material/layer, used to name the output stl file
    :type index_layer: int
    :param h: Initial height (z_min) of the slice
    :type h: float
    :param height: Height of the slice
    :type height: float

    :return: List of vertices and STL file name
    """
    # NOTE: the stencil's lateral (X/Y) size must NOT be padded beyond the atomic system's real
    # dimensions. Atomsk's "-select stl" rescales the whole STL model (X, Y, *and* Z) by a single
    # uniform factor equal to the smallest ratio between an atomic box dimension and the
    # corresponding STL dimension. An oversized X/Y footprint therefore silently compresses the Z
    # window too, shrinking every slice's actual height (e.g. a requested 25 became ~10 when this
    # box was padded by +50 in X/Y). Keeping X/Y equal to the real sample size keeps that ratio
    # close to 1, so the Z window is applied as designed, at the cost of a few-Angstrom lateral
    # edge clipping where atomsk's lattice duplication slightly overshoots the requested size.
    vertices, faces = fp.multi_layered(h, param.width, param.length, height, param.ns)

    # Creates a column that has an assigned index number for each row in vertices
    # with the addition of this new column and also returns the nodenumber which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # Nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, 0, 0)
    nodesurf = nodesurf[np.lexsort((nodesurf[:, 0], nodesurf[:, 1]))]

    xv = nodesurf[:, 0] / max(nodesurf[:, 0])
    yv = nodesurf[:, 1] / max(nodesurf[:, 1])

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the roughness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, nodesurf, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates a stl file of the box with roughness on the surface
    stl_pre = out_pre + str(index_layer)
    fp.stl_file(vertices, faces, stl_pre)
    fp.refine_3Dmesh(param.type_S, stl_pre, param.ns, param.alpha, param.ext_fem)

    return vertices, stl_pre + ".stl"


def make_atom_multilayered(param, out_pre):
    """
    Generates an atomic positions file for the multi_layered grain object: an alternating stack of
    material slices (param.pattern_layer / param.height_layer), each cut against the rough top
    surface of the slice below it and given its own rough top surface, then merged together. The
    pattern is repeated periodically to reach param.height.

    The first material is split into two half-height slices, one at the very bottom and one at the
    very top of the sample: since the sample is periodic in z, this makes the periodic seam fall
    inside a single homogeneous material instead of at a rough interface between two materials, so
    neither end of the box needs a cut against a neighbour.

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of output file
    :type out_pre: str

    :return: A Multi_layered NanoDevice, written to out_pre + ".<ext>" for every param.ext_ato extension
    """
    pattern_layer = param.pattern_layer
    height_layer = param.height_layer

    # Keep in mind that the pattern layer is periodically repeated: true_height = n_pattern x height_pattern
    height_pattern = sum(height_layer[m] for m in pattern_layer)
    n_pattern = int(param.height // height_pattern)
    if param.height % height_pattern != 0:
        print("!!!WARNING!!!,To keep the periodicity, The height of the device will be truncated to this Height:" +
              str(n_pattern * height_pattern))

    # Flatten the pattern repetitions into one ordered list of (material_index, height) slices
    # spanning the whole sample, with the first material split into two half-height slices (see
    # docstring above).
    first_material = pattern_layer[0]
    half_height = height_layer[first_material] / 2
    slices = [(first_material, half_height)]
    for j in range(n_pattern):
        for k, m in enumerate(pattern_layer):
            if j == 0 and k == 0:
                continue
            slices.append((m, height_layer[m]))
    slices.append((first_material, half_height))

    # SECURITY: files created so far, deleted on error
    file_create = [out_pre + "_stat.txt"]

    try:
        # CREATION OF ALL SUPERCELLS
        # 1 SUPERCELL PER MATERIAL, ALL WITH THE WHOLE SIZE OF THE SAMPLE
        dim_x, dim_y, dim_z = param.length, param.width, n_pattern * height_pattern

        list_supercell = [fp._atomsk_create_supercell(atoms, param, dim_x, dim_y, dim_z)
                           for atoms in range(len(param.material))]
        file_create.extend(list_supercell)

        # We deform each supercell to match its dimensions and preserve PBCs
        fp.av_length_and_strain(list_supercell, dim_z)

        # For each slice: generate its own rough top surface, then cut it out of its material's
        # supercell using that top surface and the previous slice's top surface as its bottom (the
        # very first slice has no bottom cut, since its bottom is the flat edge of the box)
        h = 0
        prev_top_stl = None
        cells = []
        for i, (material, height) in enumerate(slices):
            print("#### SLICE {}/{} (material index={}, height={}) under process...".format(
                i, len(slices) - 1, material, height))

            _, top_stl = make_multi_layered(param, out_pre, material, h, height)
            file_create.append(top_stl)
            file_create.append(out_pre + str(material) + ".msh")
            fp.remove_file(out_pre + str(material) + ".msh")
            h += height

            supercell = "mat{}_supercellm.cfg".format(material)
            cell_file = "cell{}.cfg".format(i)
            if prev_top_stl is None:
                fp._cut_top(supercell, top_stl, cell_file)
            else:
                outm = "mat{}_outm{}.cfg".format(material, i)
                fp._cut_top(supercell, top_stl, outm)
                file_create.append(outm)
                fp._cut_bottom(outm, prev_top_stl, cell_file)
                fp.remove_file(outm)
                fp.remove_file(prev_top_stl)

            file_create.append(cell_file)
            cells.append(cell_file)
            prev_top_stl = top_stl

        # The last slice's own top surface is the flat top edge of the box (it wraps around to the
        # first slice via periodicity), so it is never reused as anyone's bottom
        fp.remove_file(prev_top_stl)

        # MERGING OF ALL SLICES
        fp._merge_cfg_chain(cells, out_pre + ".cfg")
        file_create.append(out_pre + ".cfg")

        # Create the requested atomic position file(s)
        for e in param.ext_ato:
            if e != "cfg":
                subprocess.call(["atomsk", out_pre + ".cfg", out_pre + "." + e, "-v", "2"])

        # Remove all intermediate files
        for f in cells:
            fp.remove_file(f)
        for f in list_supercell:
            fp.remove_file(f)
        fp.remove_file(out_pre + "_stat.txt")

        print("JOB DONE!" + "  File name: " + out_pre + ".lmp")

    except Exception as ex:
        import traceback
        print(f"ERROR: {ex}")
        print("Detailed error traceback:")
        traceback.print_exc()
        # Delete all files created before the error
        for f in file_create:
            fp.remove_file(f)
            print(f"File deleted: {f}")
        print("Cleaning File Done")
