# ---------------------------------------------------------------------------
# Title: SAMPLE CLASS
# Authors: Jonathan Amodeo, Hugo Iteney, Javier Gonzalez, Jennifer Izaguirre, Christophe Le Bourlot, Thomas Cadart
# Date: June 01, 2022
#
# The SAMPLE class is responsible for generating the desired object shape (nanowire, slab, sphere, etc.)
# and creating the appropriate file type.
# The MAKE_STL function generates an .stl file of the shape, which is useful for FEM simulations.
# In this method, the shape is created based on user-defined parameters obtained from the PARAM class.
# The MAKE_ATOM function creates an .lmp file, which requires the .stl file generated by MAKE_STL.
# The parameters for generating the .lmp file are determined by the user's input.
# ---------------------------------------------------------------------------
#from tqdm import tqdm
import json
import os
import shutil
import tempfile
import time
import subprocess
from pathlib import Path

import numpy as np
from src import Func_pyrough as fp


class Sample:
    def __init__(self, type_sample):
        self.sample = type_sample

    def make_stl(self, param, out_pre):
        """
        Creates an stl file based on the parameters chosen by the user. Based on the type of sample
        entered, the code will sort through the options of type of samples and if true then the
        code under the type of sample will be executed. The type of sample affects the type of stl
        file returned. The code executed requires the parameters to create the object stl and to
        apply surface roughness onto the object. ...; In continuation will add that a separate
        files will be stored if they want to redo the code.

        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        :param out_pre: Prefix of the output files
        :type out_pre: str

        :returns: List of nodes and stl file name
        """
        if param.type_S == "cwire":
            vertices, _, stl, rot_stl = make_cwire(param, out_pre)
        elif param.type_S == "box":
            vertices, _, stl, rot_stl = make_box(param, out_pre)
        elif param.type_S == "sphere":
            vertices, _, stl, rot_stl = make_sphere(param, out_pre)
        elif param.type_S == "fwire":
            vertices, _, stl, rot_stl = make_fwire(param, out_pre)
        elif param.type_S == "fpillar":
            vertices, _, stl, rot_stl = make_fpillar(param, out_pre)
        elif param.type_S == "cpillar":
            vertices, _, stl, rot_stl = make_cpillar(param, out_pre)
        elif param.type_S == "wulff":
            vertices, _, stl, rot_stl = make_wulff(param, out_pre)
        elif param.type_S == "cube":
            vertices, _, stl, rot_stl = make_cube(param, out_pre)
        elif param.type_S == "lattice":
            vertices, _, stl, rot_stl = make_lattice(param, out_pre)
        else:
            raise ValueError("No valid sample type found in the JSON file.")
        return vertices, stl, rot_stl

    def make_atom(
            self,
            STL,
            param,
            vertices,
            out_pre):
        """
        Creates an atom position file sample_with_atoms.lmp. This requires a .stl file with rough surfaces
        used as a stencil over a larger block of atoms from which out-of-the-mesh atoms are removed


        :param STL: The stl file with an object that has surface roughness applied to it
        :type STL: str
        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        :param vertices: List of nodes
        :type vertices: array
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """

        dim_x = max(vertices[:, 0]) - min(vertices[:, 0])
        dim_y = max(vertices[:, 1]) - min(vertices[:, 1])
        dim_z = max(vertices[:, 2]) - min(vertices[:, 2])

        dis_x, dup_x, orien_x = fp.duplicate(dim_x, param.orien_x[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])
        dis_y, dup_y, orien_y = fp.duplicate(dim_y, param.orien_y[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])
        dis_z, dup_z, orien_z = fp.duplicate(dim_z, param.orien_z[0], param.lattice_parameter[0],
                                             param.lattice_structure[0])

        # Here we create a large block of atoms material_supercell.lmp
        subprocess.call([
            "atomsk", "--create",
            param.lattice_structure[0],
            *param.lattice_parameter[0],
            *param.material[0],
            "orient", orien_x, orien_y, orien_z,
            "-duplicate", dup_x, dup_y, dup_z,
            "material_supercell.lmp", "-v", "2",
        ])

        # Then the STL file is used as a stencil over material_supercell.lmp and extra atoms are removed
        subprocess.call([
            "atomsk", "material_supercell.lmp",
            "-select", "stl", "center", STL,
            "-select", "invert", "-rmatom", "select",
            out_pre + ".lmp",
            " ".join([x for x in param.ext_ato if x != "lmp"]),
            "-v", "2",
        ])

        Path("material_supercell.lmp").unlink(missing_ok=True)

        fp.rebox(out_pre + ".lmp", 0.001)

        # Euler rotation
        fp.lmp_rotate_euler(out_pre + ".lmp", out_pre + "_rot.lmp", param.angles2, order='zyx')

        fp.rebox(out_pre + "_rot.lmp", 0.001)

        shutil.move(out_pre + "_rot.lmp", out_pre + ".lmp")

        if param.ext_ato != ['lmp']:
            cmd = ["atomsk",
                   out_pre + ".lmp",
                   " ".join([x for x in param.ext_ato[0:] if x != "lmp"])
                   ]
            subprocess.call(cmd)

    def make_precipitate(
            self,
            STL,
            param
    ):
        """
        Creates an atom position file sample_with_atoms.lmp. This requires a .stl file with rough surfaces
        used as a stencil over a larger block of atoms from which out-of-the-mesh atoms are removed

        :param STL: The stl file with an object that has surface roughness applied to it
        :type STL: str
        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        """

        dis_x, dup_x, orien_x = fp.duplicate(param.dim_mat_x, param.orien_x, param.lattice_parameter,
                                             param.lattice_structure)
        dis_y, dup_y, orien_y = fp.duplicate(param.dim_mat_y, param.orien_y, param.lattice_parameter,
                                             param.lattice_structure)
        dis_z, dup_z, orien_z = fp.duplicate(param.dim_mat_z, param.orien_z, param.lattice_parameter,
                                             param.lattice_structure)

        cmd = [
            "atomsk",
            "--create",
            param.lattice_structure,
            *param.lattice_parameter,
            *param.material,
            "orient",
            orien_x,
            orien_y,
            orien_z,
            "-duplicate",
            dup_x,
            dup_y,
            dup_z,
            "precipitate_supercell.xyz",
            "-v ",
            "2",
        ]

        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over precipitate_supercell.lmp and extra atoms are removed
        cmd = [
            "atomsk",
            "precipitate_supercell.xyz",
            "-select",
            "stl",
            "center",
            STL,
            "-select",
            "invert",
            "-rmatom",
            "select",
            "precipitate.xyz",
            "-v",
            "2",
        ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        temp_file = "precipitate_supercell.xyz"
        if os.path.exists(temp_file):
            os.remove(temp_file)

        # Precipitate rotation : Euler rotation
        fp.xyz_rotate_euler("precipitate.xyz", "precipitate_rot.xyz", param.angles2, order='zyx')
        subprocess.call(["mv", "precipitate_rot.xyz", "precipitate.xyz"])
        subprocess.call(["rm", STL])

    def make_atom_matrix(
            self,
            ROTSTL,
            param
    ):
        """
        Creates an orthogonal matrix made of atoms.

        :param ROTSTL: The stl file with an object that has surface roughness applied to it and rotated with Euler angles
        :type ROTSTL: str
        :param param: the object containing all the parameters defined by the user in the JSON input file
        :type param: Parameter class object
        """

        dis_x, dup_x, orien_x = fp.duplicate(param.length_x, param.orien_x, param.lattice_parameter,
                                             param.lattice_structure)
        dis_y, dup_y, orien_y = fp.duplicate(param.length_y, param.orien_y, param.lattice_parameter,
                                             param.lattice_structure)
        dis_z, dup_z, orien_z = fp.duplicate(param.length_z, param.orien_z, param.lattice_parameter,
                                             param.lattice_structure)

        # Creation of a matrix of atoms i.e., a large orthogonal block of atoms
        cmd = [
            "atomsk",
            "--create",
            param.lattice_structure,
            *param.lattice_parameter,
            *param.material,
            "orient",
            orien_x,
            orien_y,
            orien_z,
            "-duplicate",
            dup_x,
            dup_y,
            dup_z,
            "matrix_tmp.xyz",
            "-v",
            "2",
        ]
        #print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        # Then the STL file is used as a stencil over material_supercell.lmp and extra atoms are removed
        if param.precpos == 'center':
            cmd = [
                "atomsk",
                "matrix.lmp",
                "-select",
                "stl",
                "center",
                ROTSTL,
                "-rmatom",
                "select",
                "matrix_w_inprint.lmp",
                "-v",
                "2",
            ]

            # print("Atomsk call:", " ".join(map(str, cmd)))
            subprocess.call(cmd)
        else:
            fp.atomsk_select_stl_local_cutin("matrix.lmp", ROTSTL, "matrix_w_inprint.lmp", param.precpos)

        subprocess.call(["rm", "matrix.lmp", ROTSTL])

    def put_prec_in_matrix(
            self,
            out_pre,
            ext_ato
    ):
        """
        Introduce a cube/sphere/wulff precipitate into a matrix

        :param out_pre_matrix: Matrix sample
        :type out_pre_matrix: str
        :param STL: The stl file with an object that has surface roughness
        :type STL: str
        :param out_pre: Prefix of the output files
        :type out_pre: str
        """
        # This atomsk call use the same STL file than for block 1 to carve out part of out_pre_matrix into mat2_out.xyz
        # As using thee same STL file but with the invert option, mat2_out.xyz is the negative of mat1_out.xyz
        cmd = [
            "atomsk",
            "--merge",
            "2",
            #"matrix_w_inprint.xyz",
            "matrix_w_inprint.lmp",
            "precipitate.xyz",
            out_pre + ".xyz",
            "-v",
            "2",
        ]
        print("Atomsk call:", " ".join(map(str, cmd)))
        subprocess.call(cmd)

        subprocess.call(["atomsk", out_pre + ".xyz", out_pre + ".lmp"])

        for e in ext_ato:
            if e != "lmp":
                subprocess.call(["atomsk", out_pre + ".lmp", out_pre + "." + e, "-v", "2"])

        #subprocess.call(["rm", "matrix.xyz", "precipitate.xyz", out_pre + ".xyz"])


def make_cwire(param, out_pre):
    """
    Creates an stl file of a rough wire

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str
    
    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, 0)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array file
    # from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, 0, 0)

    # convert to cylindrics coordinates (Rho Theta Z nodenumb)
    cy_nodesurf = np.array(
        [
            fp.rho(nodesurf[:, 0], nodesurf[:, 1]),
            fp.theta(nodesurf[:, 0], nodesurf[:, 1]),
            nodesurf[:, 2],
            nodesurf[:, 3],
        ]
    ).T

    cy_nodesurf = cy_nodesurf[np.lexsort((cy_nodesurf[:, 1], cy_nodesurf[:, 2]))]

    # creating X and Y vector (Connection matrix size) going to make one line code
    xv = (cy_nodesurf[:, 1] / max(cy_nodesurf[:, 1]) + 1) / 2
    yv = (cy_nodesurf[:, 2] / max(cy_nodesurf[:, 2]) + 1) / 2

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, cy_nodesurf, vertices, 0)

    # gets ride of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates an stl file of the cylinder with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_box(param, out_pre):
    """
    Creates an stl file of a rough box

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, param.width, param.length, param.height, 0, param.ns, 0)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, 0, 0)
    nodesurf = nodesurf[np.lexsort((nodesurf[:, 0], nodesurf[:, 1]))]

    xv = nodesurf[:, 0] / max(nodesurf[:, 0])
    yv = nodesurf[:, 1] / max(nodesurf[:, 1])

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, nodesurf, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates an stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_sphere(param, out_pre):
    """
    Creates an stl file of a rough sphere

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, 0, 0, param.radius, param.ns, 0)
    nbPoint = len(vertices)

    r = np.zeros(nbPoint)
    x, y, z, t = fp.coord_sphere(vertices)
    vert_phi_theta = fp.vertex_tp(x, y, t, z)

    thetaa = fp.theta(y, x)
    phii = fp.phi(t, z)

    # creates the displacement values of the nodes on the surface of the sphere
    r = fp.rough_matrix_sphere(nbPoint, param.B, thetaa, phii, vert_phi_theta, r)

    # creates a new matrix with x, y, z in cartesian coordinates
    C2 = 1.0 / nbPoint / param.N / 2.0
    new_vertex = fp.coord_cart_sphere(param.C1, C2, r, vertices, t, z, y, x)

    # creates an stl file of the sphere with roughness on the surface
    fp.stl_file(new_vertex, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_fwire(param, out_pre):
    """
    Creates an stl file of a rough faceted wire

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    points, angles = fp.base(param.radius, param.nfaces)

    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, points)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(
        param.type_S,
        vertices,
        nodenumber,
        points,
        0,
    )
    cy_nodesurf = fp.cart2cyl(nodesurf)
    sorted_cy_nodesurf = cy_nodesurf[np.lexsort((cy_nodesurf[:, 1], cy_nodesurf[:, 2]))]
    nodesurf = fp.cyl2cart(sorted_cy_nodesurf)

    Z = len(np.where(sorted_cy_nodesurf[:, 2] == 0)[0])
    T = len(np.unique(sorted_cy_nodesurf[:, 2]))
    xv = np.linspace(0, 1, Z)
    yv = np.linspace(0, 1, T)

    xv, yv = np.meshgrid(xv, yv)

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(param.type_S, m, n, param.N, param.M, param.B, xv, yv, sfrM, sfrN, param.C1, param.RMS, out_pre)
    vertices = fp.make_rough(param.type_S, z, nodesurf, vertices, angles)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]
    vertices = fp.align_f(vertices, angles)

    # creates an stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_wulff(param, out_pre):
    """
    Creates an stl file of a rough Wulff-shaped nanoparticle

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix for output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    obj_points, obj_faces = fp.make_obj(
        param.surfaces,
        param.energies,
        param.n_at,
        param.lattice_structure[0],
        param.lattice_parameter[0],
        param.material[0],
        param.orien_x[0],
        param.orien_z[0],
        out_pre,
    )
    vertices, faces = fp.read_stl_wulff(param.raw_stl, obj_points, obj_faces, param.ns)

    if os.path.exists(out_pre + ".obj"):
        os.remove(out_pre + ".obj")
    list_n = fp.faces_normals(obj_points, obj_faces)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumbers which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)
    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, obj_points, obj_faces)

    node_edge, node_corner = fp.node_corner(nodesurf)

    vertices = fp.make_rough_wulff(
        vertices, param.B, param.C1, param.RMS, param.N, param.M, nodesurf, node_edge, node_corner, list_n
    )

    vertices = vertices[:, :3]

    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_cube(param, out_pre):
    """
    Creates an stl file of a cubic NP

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """

    obj_points, obj_faces = fp.cube_faces(param.width, param.length, param.height)
    list_n = fp.faces_normals(obj_points, obj_faces)

    vertices, faces = fp.cube(param.width, param.length, param.height, param.ns)
    vertices, nodenumber = fp.node_indexing(vertices)

    nodesurf = fp.node_surface(param.type_S, vertices, nodenumber, obj_points, obj_faces)
    node_edge, node_corner = fp.node_corner(nodesurf)

    vertices = fp.make_rough_wulff(
        vertices, param.B, param.C1, param.RMS, param.N, param.M,
        nodesurf, node_edge, node_corner, list_n
    )

    vertices = fp.center_3d_dataset(vertices[:, :3])

    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_lattice(param, out_pre):
    """
    Creates an stl file of a lattice structure

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    try:
        import manifold3d as manifold
    except ImportError:
        raise ImportError("manifold3d library is not installed. Please install it with: pip install manifold3d")

    try:
        import trimesh
    except ImportError:
        raise ImportError("trimesh library is not installed. Please install it with: pip install trimesh")

    try:
        import pymeshlab
    except ImportError:
        raise ImportError("pymeshlab library is not installed. Please install it with: pip install pymeshlab")

    try:
        from pyLatticeDSO.src.pyLatticeDesign.lattice import Lattice
    except ImportError:
        raise ImportError("pyLatticeDSO library is not installed as submodule."
                          "Please install it to use this feature. See documentation.")

    def numpy_to_manifold(vertices, faces):
        """
        Converts numpy arrays of vertices and faces into a manifold3d Manifold object.
        This includes repairing the mesh to ensure it is watertight and suitable for boolean operations.
        """
        tmp = trimesh.Trimesh(vertices=vertices, faces=faces)
        tmp.remove_unreferenced_vertices()
        tmp.fix_normals()
        trimesh.repair.fix_winding(tmp)
        trimesh.repair.fix_normals(tmp)
        trimesh.repair.fill_holes(tmp)

        return manifold.Manifold(
            mesh=manifold.Mesh(
                vert_properties=np.array(tmp.vertices, dtype=np.float32),
                tri_verts=np.array(tmp.faces, dtype=np.uint32)
            )
        )

    # Lattice object creation
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as tmp:
        json.dump(param.geometry_lattice, tmp, indent=2)
        tmp_path = tmp.name

    try:
        lattice_object = Lattice(tmp_path)
    finally:
        os.remove(tmp_path)

    param_type_S_backup = param.type_S
    all_manifolds = []

    # Generate the rough wire mesh for each beam
    for beam in lattice_object.beams:
        p1 = np.array(beam.point1.coordinates)
        p2 = np.array(beam.point2.coordinates)
        radius = beam.initial_radius if getattr(beam, "initial_radius", None) is not None else beam.radius
        param.radius = radius
        param.length = beam.length
        if param.beam_type == "cwire":
            param.type_S = "cwire"
            vertices, faces, _, _ = make_cwire(param, out_pre)
        elif param.beam_type == "fwire":
            param.type_S = "fwire"
            vertices, faces, _, _ = make_fwire(param, out_pre)
        else:
            raise ValueError("No valid beam type found in the JSON file.")

        # Positioning the wire at the correct location
        direction = p2 - p1
        R = fp.rotation_from_z_axis(direction)
        vertices = fp.apply_rigid_transform(vertices, R, np.zeros(3))
        vertices += p1

        beam_manifold = numpy_to_manifold(vertices, faces)
        all_manifolds.append(beam_manifold)

    # Perform boolean union of all beam manifolds
    union_manifold = all_manifolds[0]
    for m in all_manifolds[1:]:
        union_manifold = union_manifold + m

    if param.trim_boundary_beams:
        x0, y0, z0 = lattice_object.x_min, lattice_object.y_min, lattice_object.z_min
        dx, dy, dz = (lattice_object.x_max - x0,
                      lattice_object.y_max - y0,
                      lattice_object.z_max - z0)

        # Generate a rough box mesh that will be used to trim the beams at the lattice boundaries
        obj_points, obj_faces = fp.cube_faces(dy, dx, dz)
        list_n = fp.faces_normals(obj_points, obj_faces)

        box_vertices, box_faces = fp.read_stl("cube", param.raw_stl, dy, dx, dz, 0, param.ns, 0)
        box_vertices, box_nodenumber = fp.node_indexing(box_vertices)

        nodesurf = fp.node_surface("cube", box_vertices, box_nodenumber, obj_points, obj_faces)
        node_edge, node_corner = fp.node_corner(nodesurf)

        C1_box = param.cube_trimmer_param.get("C1", param.C1)
        eta_box = param.cube_trimmer_param.get("eta", param.eta)
        B_box = 2 * (1 + eta_box)
        RMS_box = param.cube_trimmer_param.get("RMS", param.RMS)
        N_box = param.cube_trimmer_param.get("N", param.N)
        M_box = param.cube_trimmer_param.get("M", param.M)
        box_vertices = fp.make_rough_wulff(
            box_vertices, B_box, C1_box, RMS_box, N_box, M_box,
            nodesurf, node_edge, node_corner, list_n
        )

        # Translate the box to the correct position
        box_vertices = box_vertices[:, :3]
        box_vertices += np.array([x0, y0, z0])

        rough_box_trimesh = trimesh.Trimesh(vertices=box_vertices, faces=box_faces)
        rough_box_trimesh.remove_unreferenced_vertices()
        rough_box_trimesh.fix_normals()
        trimesh.repair.fix_winding(rough_box_trimesh)
        trimesh.repair.fill_holes(rough_box_trimesh)
        rough_box_trimesh.export(out_pre + "_rough_box.stl")

        rough_box = manifold.Manifold(
            mesh=manifold.Mesh(
                vert_properties=np.array(rough_box_trimesh.vertices, dtype=np.float32),
                tri_verts=np.array(rough_box_trimesh.faces, dtype=np.uint32)
            )
        )

        union_manifold = union_manifold ^ rough_box
        print("====== > Rough bounding box applied.")

        if union_manifold.is_empty():
            raise ValueError(
                f"Intersection vide !\n"
                f"Rough box bounds: {rough_box_trimesh.bounds}\n"
                f"Lattice: x=[{x0},{x0 + dx}], y=[{y0},{y0 + dy}], z=[{z0},{z0 + dz}]"
            )

    # Convert the final manifold back to a mesh and export as STL
    mesh = union_manifold.to_mesh()

    tmp = trimesh.Trimesh(
        vertices=mesh.vert_properties,
        faces=mesh.tri_verts
    )

    # name_mesh = out_pre + "temp.stl"
    # tmp.export(name_mesh)

    # Determine target edge length for remeshing based on the average edge length of the current mesh
    edge_lengths = tmp.edges_unique_length
    target_len = float(np.mean(edge_lengths))

    # print(f"Target edge length: {target_len:.4f}")

    bbox_diagonal = np.linalg.norm(tmp.bounds[1] - tmp.bounds[0])
    target_percentage = (target_len / bbox_diagonal) * 100

    # print(f"Target edge length: {target_len:.4f}")
    # print(f"Bbox diagonal: {bbox_diagonal:.4f}")
    # print(f"Target percentage: {target_percentage:.4f}%")
    target_percentage /= 2.0

    # Remesh the mesh using PyMeshLab to achieve a more uniform distribution of vertices
    ms = pymeshlab.MeshSet()
    ms.add_mesh(pymeshlab.Mesh(
        vertex_matrix=tmp.vertices,
        face_matrix=tmp.faces
    ))

    # Remesh the mesh using isotropic explicit remeshing to achieve a more uniform distribution of vertices
    ms.meshing_isotropic_explicit_remeshing(
        targetlen=pymeshlab.PercentageValue(target_percentage),
        iterations=5
    )

    remeshed = ms.current_mesh()
    final_mesh = trimesh.Trimesh(vertices=remeshed.vertex_matrix(), faces=remeshed.face_matrix())

    name_mesh = out_pre + ".stl"
    final_mesh.export(name_mesh)

    # Reset param.type_S to its original value for downstream processing
    param.type_S = param_type_S_backup

    # fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return mesh.vert_properties, mesh.tri_verts, out_pre + ".stl", out_pre + "_rot.stl"


def make_atom_grain(
        STL,
        param,
        vertices,
        out_pre):
    """
    Generates an atomic positions file for the grain object.

    :param STL: The stl file with an object that has surface roughness applied to it
    :type STL: str
    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param vertices: List of nodes
    :type vertices: array
    :param out_pre: Prefix of output file
    :type out_pre: str

    :return: None, but generates an atomic positions file for the grain object in the same directory as the script
    with the name out_pre.lmp
    """

    dim_x = max(vertices[:, 0]) - min(vertices[:, 0])
    dim_y = max(vertices[:, 1]) - min(vertices[:, 1])
    dim_z = max(vertices[:, 2]) - min(vertices[:, 2])

    supercell_files = []

    for i in range(len(param.material)):
        dis_x, dup_x, orien_x = fp.duplicate(dim_x, param.orien_x[i], param.lattice_parameter[i], param.lattice_structure[i])
        dis_y, dup_y, orien_y = fp.duplicate(dim_y, param.orien_y[i], param.lattice_parameter[i], param.lattice_structure[i])
        dis_z, dup_z, orien_z = fp.duplicate(2 * dim_z, param.orien_z[i], param.lattice_parameter[i], param.lattice_structure[i])

        outfile = f"mat{i+1}_supercell.cfg"
        subprocess.call([
            "atomsk", "--create",
            param.lattice_structure[i],
            *param.lattice_parameter[i],
            *param.material[i],
            "orient", orien_x, orien_y, orien_z,
            "-duplicate", dup_x, dup_y, dup_z,
            "-center", "com", outfile, "-v", "2",
        ])
        supercell_files.append(outfile)

    # Deform all materials to match mat1 dimensions
    for i in range(1, len(supercell_files)):
        fp.strain_file1_to_file2(supercell_files[i], supercell_files[0])

    # Carve mat1 with STL (keep inside)
    subprocess.call([
        "atomsk", supercell_files[0],
        "-select", "stl", STL,
        "-rmatom", "select", "mat1_out.cfg", "-v", "2",
    ])

    # Carve mat2 with STL inverted (keep outside)
    subprocess.call([
        "atomsk", supercell_files[1],
        "-select", "stl", STL,
        "-select", "invert",
        "-rmatom", "select", "mat2_out.cfg", "-v", "2",
    ])

    # Merge
    subprocess.call(["atomsk", "--merge", "2", "mat1_out.cfg", "mat2_out.cfg", "temp2.cfg", "-v", "2"])

    for e in param.ext_ato:
        subprocess.call(["atomsk", "temp2.cfg", out_pre + "." + e, "-v", "2"])

    # Cleaning
    for f in supercell_files + ["mat1_out.cfg", "mat2_out.cfg", "temp2.cfg"]:
        Path(f).unlink(missing_ok=True)


def make_fpillar(param, out_pre):
    """
    Creates an stl file of a rough faceted pillar

    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name for a Faceted Pillar
    """
    # create the base of the faceted Pillar
    points, anglesfac = fp.base(param.radius, param.nfaces)

    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, points)

    # creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumber which is an array
    # filled from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # nodes at the surface of the object. These nodes will have the surface roughness applied to it
    # nodesurf 1 is the faceted wire surface, and nodesurf2 is the topside surface
    nodesurf1 = fp.node_surface("fwire", vertices, nodenumber, points, 0)
    nodesurf2 = fp.node_surface("box", vertices, nodenumber, 0, 0)

    # Save the index of nodes which are on the edge of the pillar
    nodesurftot = [nodesurf1] + [nodesurf2]
    node_edge, node_corner = fp.node_corner(nodesurftot)

    # convert to cylindrics coordinates (Rho Theta Z nodenumber)
    cy_nodesurf1 = fp.cart2cyl(nodesurf1)
    sorted_cy_nodesurf1 = cy_nodesurf1[np.lexsort((cy_nodesurf1[:, 1], cy_nodesurf1[:, 2]))]
    nodesurf1 = fp.cyl2cart(sorted_cy_nodesurf1)

    Z = len(np.where(sorted_cy_nodesurf1[:, 2] == 0)[0])
    T = len(np.unique(sorted_cy_nodesurf1[:, 2]))

    xv1 = np.linspace(0, 1, Z)
    yv1 = np.linspace(0, 1, T)
    xv1, yv1 = np.meshgrid(xv1, yv1)
    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m1, n1 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    xv2 = nodesurf2[:, 0] / max(nodesurf2[:, 0])
    yv2 = nodesurf2[:, 1] / max(nodesurf2[:, 1])
    m2, n2 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # Array these represent the roughness on the surface
    z1 = fp.random_surf2("fwire", m1, n1, param.N, param.M, param.B1, xv1, yv1, sfrM, sfrN, param.C1, param.RMS1, out_pre)
    z2 = fp.random_surf2("box", m2, n2, param.N, param.M, param.B2, xv2, yv2, sfrM, sfrN, param.C2, param.RMS2, out_pre)

    # Displace nodes to make surfaces rough, nodes on the edge are displace 2 times so these displacement should be
    # normalised
    vertices = fp.make_rough_pillar(param.type_S, z1, z2, nodesurf1, nodesurf2, node_edge, vertices, anglesfac)
    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    vertices = fp.align_f(vertices, anglesfac)
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_cpillar(
        param,
        out_pre,
):
    """
    :param param: the object containing all the parameters defined by the user in the JSON input file
    :type param: Parameter class object
    :param out_pre: Prefix of the output files
    :type out_pre: str

    :return: List of vertices, faces, STL file name, and rotated STL file name for a circular Pillar
    """
    if len(param.eta == 1):
        B = [param.B, param.B]
        C1 = [param.C1, param.C1]
        RMS = [param.RMS, param.RMS]
    else:
        B = [param.B[0], param.B[1]]
        C1 = [param.C1[0], param.C1[1]]
        RMS = [param.RMS[0], param.RMS[1]]

    vertices, faces = fp.read_stl(param.type_S, param.raw_stl, 0, param.length, 0, param.radius, param.ns, 0)

    # Creates a column that has an assigned index number for each row in vertices; returns vertices
    # with the addition of this new column and also returns the nodenumber which is an array file
    # from 0 - length of the vertices
    vertices, nodenumber = fp.node_indexing(vertices)

    # Nodes at the surface of the object. These nodes will have the surface roughness applied to it
    # nodesurf 1 is the wire surface, and nodesurf2 is the topside surface
    nodesurf1 = fp.node_surface("cwire", vertices, nodenumber, 0, 0)
    nodesurf2 = fp.node_surface("box", vertices, nodenumber, 0, 0)

    # Getting the index of nodes on the edge
    nodesurftot = [nodesurf1] + [nodesurf2]
    node_edge, node_corner = fp.node_corner(nodesurftot)

    # Convert to cylindrics coordinates (Rho Theta Z nodenumber)
    cy_nodesurf1 = np.array(
        [
            fp.rho(nodesurf1[:, 0], nodesurf1[:, 1]),
            fp.theta(nodesurf1[:, 0], nodesurf1[:, 1]),
            nodesurf1[:, 2],
            nodesurf1[:, 3],
        ]
    ).T

    cy_nodesurf1 = cy_nodesurf1[np.lexsort((cy_nodesurf1[:, 1], cy_nodesurf1[:, 2]))]

    # Creating X and Y vector (Connection matrix size) going to make one line code
    xv1 = (cy_nodesurf1[:, 1] / max(cy_nodesurf1[:, 1]) + 1) / 2
    yv1 = (cy_nodesurf1[:, 2] / max(cy_nodesurf1[:, 2]) + 1) / 2

    sfrN, sfrM = fp.vectors(param.N, param.M)  # creating vectors for M and N
    m1, n1 = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    xv2 = nodesurf2[:, 0] / max(nodesurf2[:, 0])
    yv2 = nodesurf2[:, 1] / max(nodesurf2[:, 1])
    m2, n2 = fp.random_numbers(sfrN, sfrM)

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # Array these represent the roughness on the surface
    z1 = fp.random_surf2("cwire", m1, n1, param.N, param.M, B[0], xv1, yv1, sfrM, sfrN, C1[0], RMS[0], out_pre)
    z2 = fp.random_surf2("box", m2, n2, param.N, param.M, B[1], xv2, yv2, sfrM, sfrN, C1[1], RMS[1], out_pre)

    vertices = fp.make_rough_pillar(param.type_S, z1, z2, cy_nodesurf1, nodesurf2, node_edge, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates a stl file of the cylinder with roughness on the surface
    fp.stl_file(vertices, faces, out_pre)
    fp.refine_3Dmesh(param.type_S, out_pre, param.ns, param.alpha, param.ext_fem)

    fp.stl_rotate_euler(out_pre + ".stl", out_pre + "_rot.stl", param.angles, order='zyx')

    return vertices, faces, out_pre + ".stl", out_pre + "_rot.stl"


def make_multi_layered(
        type_sample,
        j,
        h,
        B,
        C1,
        RMS,
        N,
        M,
        length,
        height,
        width,
        ns,
        alpha,
        raw_stl,
        out_pre,
        ext_fem,
):
    """
    Creates an stl file of a rough box using to make a multi_layered grain

    :param type_sample: The name of the sample
    :type type_sample: str
    :param j : the index of the box stl used to build the final Multi_layered Device
    :type j : int
    :param h : Initial height z_min == h
    :type h : float
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Length of the box
    :type length: float
    :param height: Height of the box
    :type height: float
    :param width: Width of the box
    :type width: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param out_pre: Prefix of the output files
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list

    :return: List of vertices, faces, STL file name, and rotated STL file name
    """
    #Create a box perfect mesh at an initial height h
    vertices, faces = fp.multi_layered(h, width, length, height, ns)

    #Creates a column that has an assigned index number for each row in vertices
    #with the addition of this new column and also returns the nodenumber which is an array
    #filled from 0 - length of the vertices

    vertices, nodenumber = fp.node_indexing(vertices)

    #Nodes at the surface of the object. These nodes will have the surface roughness applied to it
    nodesurf = fp.node_surface(type_sample, vertices, nodenumber, 0, 0)
    nodesurf = nodesurf[np.lexsort((nodesurf[:, 0], nodesurf[:, 1]))]

    xv = nodesurf[:, 0] / max(nodesurf[:, 0])
    yv = nodesurf[:, 1] / max(nodesurf[:, 1])

    sfrN, sfrM = fp.vectors(N, M)  # creating vectors for M and N
    m, n = fp.random_numbers(sfrN, sfrM)  # normal gaussian for the amplitude

    # Returns an array with the Z values that will replace the previous z values in the vertices
    # array these represent the rougness on the surface
    z = fp.random_surf2(type_sample, m, n, N, M, B, xv, yv, sfrM, sfrN, C1, RMS, out_pre)
    vertices = fp.make_rough(type_sample, z, nodesurf, vertices, 0)

    # gets rid of the index column because stl file generator takes only a matrix with 3 columns
    vertices = vertices[:, :3]

    # creates a stl file of the box with roughness on the surface
    fp.stl_file(vertices, faces, out_pre + str(j))
    #fp.refine_3Dmesh(type_sample, out_pre+str(j) , ns, alpha, ext_fem)

    return vertices, out_pre + str(j) + ".stl",


def make_atom_multilayered(
        type_sample,
        height_layer,
        pattern_layer,
        B,
        C1,
        RMS,
        N,
        M,
        length,
        height,
        width,
        ns,
        alpha,
        raw_stl,
        lattice_structure,
        lattice_parameter,
        material,
        orien_x0,
        orien_y0,
        orien_z0,
        out_pre,
        ext_fem,
        ext_ato,
):
    """
    Generates an atomic positions file for the multi_layer grain object.

    :param type_sample: The name of the sample
    :type type_sample: str
    :param pattern_layer: pattern of materials deposition
    :type pattern_layer: list
    :param height_layer: height of each layer
    :type height_layer: list
    :param B: The degree the roughness is dependent on
    :type B: float
    :param C1: Roughness normalization factor
    :type C1: float
    :param RMS: RMS
    :type RMS: float
    :param N: Scaling cartesian position
    :type N: int
    :param M: Scaling cartesian position
    :type M: int
    :param length: Dimension of the Multi_layer
    :type length: float
    :param height: Dimension of the Multi_layer
    :type height: float
    :param width: Dimension of the Multi_layer
    :type width: float
    :param ns: The number of segments desired
    :type ns: int
    :param alpha: Refine mesh factor
    :type alpha: float
    :param raw_stl: Name of the input stl file
    :type raw_stl: str
    :param lattice_structure: list which contains The lattice structure of crystals
    :type lattice_structure: list
    :param lattice_parameter: list which contains The lattice parameter of crystals in Angstrom
    :type lattice_parameter: list
    :param material: List of The chemical symbol of desired elements
    :type material: list
    :param orien_x: The orientation of crystals in the x direction, list of sublist
    :type orien_x: list
    :param orien_y: The orientation of crystals in the y direction, list of sublist
    :type orien_y: list
    :param orien_z: The orientation of crystals in the z direction, list of sublist
    :type orien_z: list
    :param out_pre: Prefix of output file
    :type out_pre: str
    :param ext_fem: List of FEM extension files
    :type ext_fem: list
    :param ext_ato: Atomic position file format list
    :type ext_ato: list

    :return: A Multi_layered NanoDevices
    """

    #Compute the height of the multi-layered object (height_pattern), using the height of each layer
    # global roughness_or_not_test
    height_pattern = 0
    for hl in range(len(pattern_layer)):
        index_layer = pattern_layer[hl]
        height_pattern = height_pattern + height_layer[index_layer]

    #Size check: height_pattern vs. user-defined size (Height, in the .json file) of the multi-layered object
    #Keep in mind that the pattern layer is periodically repeated : true_height = n_pattern x height_pattern
    n_pattern = int(height // height_pattern)
    if height % height_pattern != 0:
        print("!!!WARNING!!!,To keep the periodicity, The height of the device will be truncated to this Height:" + str(
            n_pattern * height_pattern))

    #SECURITY ##############
    file_create = [out_pre + "_stat.txt"]
    #######################

    # CREATION OF ALL SUPERCELLS
    # 1 SUPERCELL PER MATERIAL, ALL WITH THE WHOLE SIZE OF THE SAMPLE
    try:
        #Initialise dimension of the supercell
        dim_x = length
        dim_y = width
        dim_z = n_pattern * height_pattern

        #Create supercells and register their file in a list
        list_supercell = []
        for atoms in range(len(material)):
            #dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x0[atoms], lattice_parameter[atoms], lattice_structure[atoms])
            #dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y0[atoms], lattice_parameter[atoms], lattice_structure[atoms])
            #dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z0[atoms], lattice_parameter[atoms], lattice_structure[atoms])
            #print("atoms : {}, dim_z {}, orien_z0[atoms] {}".format(atoms, dim_z, orien_z0[atoms]))

            #print("atoms / material : {} {}".format(atoms, len(material)))
            #print("len(lattice_structure[atoms]) : {}".format(len(lattice_structure[atoms])))
            #Here we generate blocks of atoms : mats_supercells.cfg
            if isinstance(lattice_structure[atoms], list) and len(lattice_structure[atoms]) > 1:
                # Binary random solid solution
                #print("if case")
                dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms][0])
                dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms][0])
                dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms][0])
                cmd = ["atomsk", "--create", str(lattice_structure[atoms][0]), str(*lattice_parameter[atoms]),
                       str(material[atoms][0]),
                       "orient", str(orien_x), str(orien_y), str(orien_z),
                       "-duplicate", str(dup_x), str(dup_y), str(dup_z),
                       "-select", "random", str(lattice_structure[atoms][1]) + "%", str(material[atoms][0]),
                       "-substitute",
                       str(material[atoms][0]), str(material[atoms][1]),
                       "-center", "com", "mat" + str(atoms) + "_supercellm.cfg", "-v", "1"]
                print("Atomsk binary solution {}".format(cmd))
                subprocess.call(cmd)
                print("last file create is {}:".format("mat" + str(str(atoms)) + "_supercellm.cfg"))
            else:
                # Regular crystalline structure (as usually defined in Atomsk)
                #print("else case")
                dis_x, dup_x, orien_x = fp.duplicate(dim_x, orien_x0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms])
                dis_y, dup_y, orien_y = fp.duplicate(dim_y, orien_y0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms])
                dis_z, dup_z, orien_z = fp.duplicate(dim_z, orien_z0[atoms], lattice_parameter[atoms],
                                                     lattice_structure[atoms])
                #print("lattice_structure[atoms] : 0 = {}, 1 = {}, 2 = {}".format(lattice_structure[atoms][0], lattice_structure[atoms][1], lattice_structure[atoms][2]))
                cmd = ["atomsk", "--create", str(lattice_structure[atoms]), *lattice_parameter[atoms], *material[atoms],
                       "orient", str(orien_x), str(orien_y), str(orien_z),
                       "-duplicate", str(dup_x), str(dup_y), str(dup_z),
                       "-center", "com", "mat" + str(atoms) + "_supercellm.cfg", "-v", "1"]
                print("cmd : {}".format(cmd))
                subprocess.call(cmd)

            list_supercell.append("mat" + str(atoms) + "_supercellm.cfg")
            #list_supercell_out.append("toto" + str(atoms) + "_supercellm.cfg")

            # SECURITY ##############
            file_create.append("mat" + str(atoms) + "_supercellm.cfg")
            #######################

        # We deform each supercells to match their dimensions and preserve PBCs
        fp.av_length_and_strain(list_supercell, dim_z)

        # n is the index of a cell in a pattern of the Multi_layer, h is the initial height of the cell
        n, h = 0, 0

        # Initialise a list which will contain all patterns of the multi-layered object
        List_patterns = []
        for j in range(n_pattern):
            # Loop on the number of repetition of the main pattern (e.g., we want to repet 3x the pattern_layer=[0,1,2,1])
            if j == 0:
                # 1st pattern : the first slice is only half-height
                List_cells = []  # list of material slices
                for n in range(len(pattern_layer)):
                    #In the j_th pattern, loop on each slice of material
                    #We define the geometry of the material, create an .stl file and remove exceeding atoms
                    print("#### SLICE n={}/{} in pattern j={}/{} under process...".format(n, len(pattern_layer) - 1, j,
                                                                                          n_pattern - 1))
                    if n == 0:
                        # WARNING: the 1st slice of material (n=0) in the 1st pattern (j=0) has only a half-height
                        # the second-half will be pasted at the end of the sample to ensure periodicity

                        # Determine which material is concerned at the beginning
                        index_layer1 = pattern_layer[n]
                        # Use the Height of the material concerned at the beginning
                        height_layern = height_layer[index_layer1]
                        print("FEM_STL1, height_layern is {}, will be divided by 2 as n=j={}".format(height_layern, n))

                        vertices, FEM_STL1 = make_multi_layered(
                            type_sample,
                            index_layer1,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern / 2,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL1)
                        #file_create.append(out_pre + str(index_layer1) + ".msh")
                        #######################

                        #a = ""
                        #subprocess.call(["rm", out_pre + str(index_layer1) + ".msh"])
                        # Atomsk uses the .stl file to remove all atoms which are not in the position of the stl file
                        print("Atomsk run invert selection (top surface) : it cuts what is out of the STL")
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "cell" + str(n) + ".cfg",
                                "-v",
                                "1"
                            ]
                        )

                        # SECURITY ##############
                        #file_create.append("mat" + str(index_layer1) + "_outm.cfg")
                        #######################

                        # Register the first cell in the merge list
                        #subprocess.call(["mv", "mat" + str(index_layer1) + "_outm.cfg", "cell" + str(n) + ".cfg"])
                        #List_cells = List_cells + ["cell" + str(0) + ".cfg"]
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]

                        # SECURITY ##############
                        #file_create.append("cell" + str(0) + ".cfg")
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        h = 0 + height_layern / 2

                    elif n % 2 != 0:
                        # ODD SLICE (1, 3, 5, .... slice starts at 0) : they have the negative bottom roughness of the n-1 layer (no new .stl1) but a new top roughness (new .stl2)
                        # e.g., slice n=1 has the negative bottom roughness of slice n=0 (re-use of .stl1 file) but a new top roughness (new .stl2 file)
                        print("We are in the odd slice j={}, n={}".format(j, n))

                        # Determine which material is concerned
                        index_layer2 = pattern_layer[n]
                        # Use the Height of the material concerned
                        height_layern = height_layer[index_layer2]

                        print("FEM_STL2, height_layern is {}".format(height_layern))

                        vertices, FEM_STL2 = make_multi_layered(
                            type_sample,
                            index_layer2,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL2)
                        #######################

                        # Top roughness treatment:
                        print(
                            "Atomsk run invert selection (rough top surface - flat bottom) : it cuts what is out of the STL")
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer2) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-v",
                                "1"
                            ]
                        )
                        #subprocess.call(cmd)
                        print("top roughness is ok")

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer2) + "_outm.cfg")
                        #######################

                        # Bottom roughness treatment:
                        # use n-1 .stl file to generate the bottom roughness
                        #subprocess.call(
                        #print("C1 = {}, {} : eta = {}, {}, RMS = {}, {}".format(C1, type(C1), (B/2)-1, type(B), RMS, type(RMS)))

                        #if not C1:
                        #    print("C1 vide")
                        #if C1 is None:
                        #    print("C1 None")
                        #print("eta : {}, B {}".format((B/2)-1, B))

                        # Here we test if the multilayered systems has rough GBs or purely flat via eta, C1 and RMS, but they have to be defined
                        if 'C1' in locals() and C1:
                            print("C1 test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(C1) > 0.001
                        if 'RMS' in locals() and RMS:
                            print("RMS test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(RMS) > 0.01

                        #print("roughness_or_not_test : {}".format(roughness_or_not_test))
                        if roughness_or_not_test:
                            print(
                                "Atomsk run a regular selection (bottom surface) : it cuts what is in the previous STL (no invert)")
                            cmd = [
                                "atomsk",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-rmatom",
                                "select",
                                "matf_outm.cfg",
                                "-v",
                                "1"
                            ]
                            print("atomsk cmd = {}".format(cmd))
                            subprocess.call(cmd)
                        else:
                            print("Perfectly-flat multi-layer, we skip the bottom surface treatment for n=2k+1")
                            subprocess.call(['cp', "mat" + str(index_layer2) + "_outm.cfg", "matf_outm.cfg"])

                        # SECURITY ##############
                        file_create.append("matf_outm.cfg")
                        #######################

                        # Register the cell file
                        shutil.move("matf_outm.cfg", "cell" + str(n) + ".cfg")
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        # Cleaning all undesirable file
                        for f in [FEM_STL2, "mat" + str(index_layer2) + "_supercellm.cfg", "mat" + str(index_layer2) + "_outm.cfg"]:
                            if os.path.exists(f):
                                os.remove(f)

                        print("bottom roughness is ok")
                        h = h + height_layern

                    elif n % 2 == 0:
                        # Even SLICE (2, 4, 6,...) : they have the negative bottom roughness of the n-1 layer but a new top roughness
                        # e.g., slice n=2 the .stl2 file negative of n=1 for bottom roughness, but need a new top roughness called .stl1 again
                        print("We are in the even slice n={}".format(n))

                        # Top roughness treatment:
                        # Determine which material is concerned
                        index_layer1 = pattern_layer[n]
                        height_layern = height_layer[index_layer1]

                        # Use the Height of the material concerned
                        vertices, FEM_STL1 = make_multi_layered(
                            type_sample,
                            index_layer1,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL1)
                        file_create.append(out_pre + str(index_layer1) + ".msh")
                        #######################

                        if os.path.exists(out_pre + str(index_layer1) + ".msh"):
                            os.remove(out_pre + str(index_layer1) + ".msh")
                        a = str(n)

                        # Bottom roughness treatment (with fresh .stl1):
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-v",
                                "2",
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_supercellm" + a + ".cfg")
                        #######################

                        # Cleaning the STL of the previous cell
                        subprocess.call(["rm", FEM_STL2, ])

                        # Top roughness treatment (with fresh .stl1):
                        # Atomsk uses the .stl file to Remove all atoms which are not in the stl file
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_outm.cfg",
                                "-v",
                                "2"
                            ]
                        )
                        #else:
                        #    print("Perfectly-flat multi-layer, we skip the surface treatment")
                        #    subprocess.call(['cp', "mat" + str(index_layer1) + "_supercellm" + a + ".cfg", "mat" + str(index_layer1) + "_outm.cfg"])

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_outm.cfg")
                        #######################

                        # Register the file in the cells file
                        subprocess.call(["mv", "mat" + str(index_layer1) + "_outm.cfg", "cell" + str(n) + ".cfg"])
                        subprocess.call(["rm", "mat" + str(index_layer1) + "_supercellm" + a + ".cfg", ])

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        FEM_STL2 = FEM_STL1
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]
                        h = h + height_layern


            elif j != 0:
                # For next patterns, we dont manage the half-height first slice of material

                List_cells = []
                for n in range(len(pattern_layer)):
                    print("#### SLICE n={}/{} in pattern j={}/{} under process...".format(n, len(pattern_layer) - 1, j,
                                                                                          n_pattern - 1))

                    if n % 2 != 0:
                        # Determine which material is concerned
                        index_layer2 = pattern_layer[n]
                        # Use the Height of the material concerned
                        height_layern = height_layer[index_layer2]

                        vertices, FEM_STL2 = make_multi_layered(
                            type_sample,
                            index_layer2,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL2)
                        #file_create.append(out_pre + str(index_layer2) + ".msh")
                        #######################

                        # Atomsk uses the .stl file to remove all toms which are not in the STL file
                        # located cut-out : top surface rough but flat bottom surface that will be process afterwards using
                        # previous .stl
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer2) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer2) + "_outm.cfg",
                                "-v",
                                "2"
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer2) + "_outm.cfg")
                        #######################

                        # Remove all atoms which are already in the previous cell
                        #if float(C1) > 0.01 and float(B) < 10.0 and float(RMS) > 0.01:
                        if 'C1' in locals() and C1:
                            print("C1 test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(C1) > 0.001
                        if 'RMS' in locals() and RMS:
                            print("RMS test")
                            roughness_or_not_test = (B / 2) - 1 < 10.0 and float(RMS) > 0.01

                        #print("roughness_or_not_test : {}".format(roughness_or_not_test))
                        if roughness_or_not_test:
                            print(
                                "Atomsk run a regular selection (bottom surface) : it cuts what is in the previous STL (no invert)")

                            subprocess.call(
                                [
                                    "atomsk",
                                    "mat" + str(index_layer2) + "_outm.cfg",
                                    "-select",
                                    "stl",
                                    FEM_STL1,
                                    "-rmatom",
                                    "select",
                                    "matf_outm.cfg",
                                    "-v",
                                    "2"
                                ]
                            )
                        else:
                            print(
                                "Perfectly-flat multi-layer, we skip the bottom surface treatment to avoid Atomsk problem with empty region")
                            subprocess.call(['cp', "mat" + str(index_layer2) + "_outm.cfg", "matf_outm.cfg"])

                        # SECURITY ##############
                        file_create.append("matf_outm.cfg")
                        #######################

                        # Register the cell file
                        subprocess.call(["mv", "matf_outm.cfg", "cell" + str(n) + ".cfg"])
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        # Cleaning all undesirable file
                        subprocess.call(
                            [
                                "rm",
                                FEM_STL1,
                                "mat" + str(index_layer2) + "_outm.cfg",
                                out_pre + "_stat.txt",
                            ]
                        )
                        h = h + height_layern

                    elif n % 2 == 0:
                        # Determine which material is concerned
                        index_layer1 = pattern_layer[n]
                        height_layern = height_layer[index_layer1]
                        # Use the Height of the material concerned

                        vertices, FEM_STL1 = make_multi_layered(
                            type_sample,
                            index_layer1,
                            h,
                            B,
                            C1,
                            RMS,
                            N,
                            M,
                            length + 50,
                            height_layern,
                            width + 50,
                            ns,
                            alpha,
                            raw_stl,
                            out_pre,
                            ext_fem,
                        )

                        # SECURITY ##############
                        file_create.append(FEM_STL1)
                        file_create.append(out_pre + str(index_layer1) + ".msh")
                        #######################

                        if os.path.exists(out_pre + str(index_layer1) + ".msh"):
                            os.remove(out_pre + str(index_layer1) + ".msh")
                        a = str(n)
                        # Remove atoms which are already in the previous cell
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm.cfg",
                                "-select",
                                "stl",
                                FEM_STL2,
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-v",
                                "2"
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_supercellm" + a + ".cfg")
                        #######################

                        # Cleaning the STL of the previous cell
                        if os.path.exists(FEM_STL2):
                            os.remove(FEM_STL2)

                        # Atomsk uses the .stl file to Remove all atoms which are not in the stl file
                        subprocess.call(
                            [
                                "atomsk",
                                "mat" + str(index_layer1) + "_supercellm" + a + ".cfg",
                                "-select",
                                "stl",
                                FEM_STL1,
                                "-select",
                                "invert",
                                "-rmatom",
                                "select",
                                "mat" + str(index_layer1) + "_outm.cfg",
                                "-v",
                                "2"
                            ]
                        )

                        # SECURITY ##############
                        file_create.append("mat" + str(index_layer1) + "_outm.cfg")
                        #######################

                        # Register the file in the cells file
                        shutil.move("mat" + str(index_layer1) + "_outm.cfg", "cell" + str(n) + ".cfg")
                        if os.path.exists("mat" + str(index_layer1) + "_supercellm" + a + ".cfg"):
                            os.remove("mat" + str(index_layer1) + "_supercellm" + a + ".cfg")

                        # SECURITY ##############
                        file_create.append("cell" + str(n) + ".cfg")
                        #######################

                        FEM_STL2 = FEM_STL1
                        List_cells = List_cells + ["cell" + str(n) + ".cfg"]
                        h = h + height_layern

            # MERGING OF THE MATERIAL SLICES FOR EACH PATTERN
            #Case with 1 cell/slice of material : register the cell/slice as the pattern
            if len(List_cells) == 1:
                shutil.move(List_cells[0], "pattern" + str(j) + ".cfg")

                # SECURITY ##############
                file_create.append("pattern" + str(j) + ".cfg")
                #######################

            #Case with many cells/slices : merge all cells of the pattern then register the final file in the pattern list
            else:
                for merge in range(len(List_cells) - 1):
                    if merge == 0:
                        subprocess.call(
                            ["atomsk", "--merge", "2", List_cells[0], List_cells[1], "celltot" + str(0) + ".cfg", "-v",
                             "2"])

                        # SECURITY ##############
                        file_create.append("celltot" + str(0) + ".cfg")
                        #######################



                    else:
                        subprocess.call(
                            ["atomsk", "--merge", "2", "celltot" + str(merge - 1) + ".cfg", List_cells[merge + 1],
                             "celltot" + str(merge) + ".cfg", "-v", "2"])
                        #Cleaning
                        if os.path.exists("celltot" + str(merge - 1) + ".cfg"):
                            os.remove("celltot" + str(merge - 1) + ".cfg")

                        # SECURITY ##############
                        file_create.append("celltot" + str(merge) + ".cfg")
                        #######################

                shutil.move("celltot" + str(len(List_cells) - 1 - 1) + ".cfg", "pattern" + str(j) + ".cfg")

                #SECURITY ##############
                file_create.append("pattern" + str(j) + ".cfg")
                #######################

            if os.path.exists(out_pre + "_stat.txt"):
                os.remove(out_pre + "_stat.txt")
            List_patterns.append("pattern" + str(j) + ".cfg")

            for m in range(len(List_cells)):
                # Cleaning all cells .cfg
                if os.path.exists(List_cells[m]):
                    os.remove(List_cells[m])

        # MERGING OF THE PATTERNS
        # Case with 1 pattern :
        if len(List_patterns) == 1:
            shutil.move(List_patterns[0], out_pre + "0.cfg")
        # Case with many patterns : Merge all patterns together
        else:
            for merge in range(len(List_patterns) - 1):
                if merge == 0:
                    subprocess.call(
                        ["atomsk", "--merge", "2", List_patterns[0], List_patterns[1], "patterntot" + str(0) + ".cfg",
                         "-v", "2"])

                    # SECURITY ##############
                    file_create.append("patterntot" + str(0) + ".cfg")
                    #######################

                else:
                    subprocess.call(
                        ["atomsk", "--merge", "2", "patterntot" + str(merge - 1) + ".cfg", List_patterns[merge + 1],
                         "patterntot" + str(merge) + ".cfg", "-v", "2"])
                    #Cleaning
                    if os.path.exists("patterntot" + str(merge - 1) + ".cfg"):
                        os.remove("patterntot" + str(merge - 1) + ".cfg")

                    # SECURITY ##############
                    file_create.append("patterntot" + str(merge) + ".cfg")
                    #######################

            shutil.move("patterntot" + str(len(List_patterns) - 1 - 1) + ".cfg", out_pre + "0.cfg")

        # SECURITY ##############
        file_create.append(out_pre + "0.cfg")
        #######################

        # ADD OF THE ENDING-SAMPLE HALF-HEIGHT OF THE FIRST SLICE OF MATERIAL (PBCs)
        #Complete the final empty part with the first material used to keep the vertical periodicity
        vertices, END = make_box("box", B, C1, RMS, N, M, length + 50, h - height_layern, width + 50, ns, alpha,
                                 raw_stl, "final", ext_fem)
        subprocess.call(
            ["atomsk", "mat" + str(pattern_layer[0]) + "_supercellm.cfg", "-select", "stl", FEM_STL2, "-rmatom",
             "select", "end0.cfg", "-v", "2"])
        subprocess.call(["atomsk", "end0.cfg", "-select", "stl", END, "-rmatom", "select", "final0.cfg", "-v", "2"])
        subprocess.call(["atomsk", "--merge", "2", out_pre + "0.cfg", "final0.cfg", out_pre + ".cfg", "-v",
                         "2"])  # merge the end to the object create

        # SECURITY ##############
        file_create.append("end0.cfg")
        file_create.append(END)
        file_create.append("final0.cfg")
        file_create.append(out_pre + ".cfg")
        file_create.append("final_stat.txt")
        file_create.append("final_stat.msh")
        #######################

        #Create the lmp file
        for e in ext_ato:
            if e != "cfg":
                subprocess.call(["atomsk", out_pre + ".cfg", out_pre + "." + e, "-v", "2"])

        #Remove all files
        list_files_to_remove = ["patterntot" + str(i) + ".cfg" for i in range(len(List_patterns) - 1)] + [
            "final0.cfg", out_pre + "0.cfg", out_pre + "1.cfg", END, "end0.cfg", "final.msh", "final_stat.txt"]
        for f in list_files_to_remove:
            if os.path.exists(f):
                os.remove(f)

        #Clean all patterns files
        for m in range(len(List_patterns)):
            # Cleaning all cells .cfg
            if os.path.exists(List_patterns[m]):
                os.remove(List_patterns[m])

        #Clean the rest of files :
        if os.path.exists(FEM_STL2):
             os.remove(FEM_STL2)
        if os.path.exists(out_pre + "_stat.txt"):
            os.remove(out_pre + "_stat.txt")
        for suppr in range(len(list_supercell)):
            # Cleaning all cells .cfg
            if os.path.exists(list_supercell[suppr]):
                os.remove(list_supercell[suppr])

        subprocess.call(["clear", ])
        print("JOB DONE!" + "  File name: " + out_pre + ".lmp")

    except Exception as ex:
        import traceback
        print(f"ERROR: {ex}")
        print("Detailed error traceback:")
        traceback.print_exc()
        #Delete all files created before the error
        for f in file_create:
            if os.path.exists(f):
                os.remove(f)
            print(f"File deleted: {f}")
        print("Cleaning File Done")
